### ISSUE TITLE
[Brewmaster] SteamOS freezes when attaching additional XBOX360 controlers

### ISSUE THREAD

**Issue by jazz1138** [ValveSoftware/SteamOS#364] opened 2015-08-30 11:51 UTC
Hi, I noticed last week that The entire system locks up (e.g. video freezes audio goes into loop, no network ping) when powering on/off a second wireless XBOX360 controller or even attaching a second wired controller in SteamOS brewmaster-beta on my Alienware Alpha. I had friends coming over to play Rocket League split screen so I didn't investigate at the time and just reverted to Alchemist. I have now just done a clean install of Brewmaster on the Beta channel. The same thing occurs.

Here is a tail of /var/log/syslog. The bit after the gap is where I powered of the second controller. (It was booted with the second controller powered on). The same occurs if you boot with it powered off and then switch it on while in the OS.

<code>
Aug 30 20:52:46 steamos kernel: [   14.927151]  [<ffffffffa05a1829>] ? xpad_init_input+0x3b9/0x3e0 [xpad]
Aug 30 20:52:46 steamos kernel: [   14.927153]  [<ffffffffa05a1e22>] ? presence_work_function+0x22/0x60 [xpad]
Aug 30 20:52:46 steamos kernel: [   14.927156]  [<ffffffff81082c5e>] ? process_one_work+0x14e/0x3f0
Aug 30 20:52:46 steamos kernel: [   14.927158]  [<ffffffff8108360b>] ? worker_thread+0x6b/0x4a0
Aug 30 20:52:46 steamos kernel: [   14.927160]  [<ffffffff810835a0>] ? rescuer_thread+0x290/0x290
Aug 30 20:52:46 steamos kernel: [   14.927162]  [<ffffffff81088363>] ? kthread+0xd3/0xf0
Aug 30 20:52:46 steamos kernel: [   14.927163]  [<ffffffff81088290>] ? kthread_create_on_node+0x180/0x180
Aug 30 20:52:46 steamos kernel: [   14.927166]  [<ffffffff81547c18>] ? ret_from_fork+0x58/0x90
Aug 30 20:52:46 steamos kernel: [   14.927168]  [<ffffffff81088290>] ? kthread_create_on_node+0x180/0x180
Aug 30 20:52:46 steamos kernel: [   14.927169] ---[ end trace 35dcd3fe75ffd823 ]---

Aug 30 20:54:32 steamos kernel: [  120.423463] ------------[ cut here ]------------
Aug 30 20:54:32 steamos kernel: [  120.423469] WARNING: CPU: 2 PID: 51 at /usr/src/packages/BUILD/linux-3.18.19/fs/sysfs/dir.c:31 sysfs_warn_dup+0x5f/0x70()
Aug 30 20:54:32 steamos kernel: [  120.423470] sysfs: cannot create duplicate filename '/devices/pci0000:00/0000:00:14.0/usb3/3-9/leds/xpad0'
Aug 30 20:54:32 steamos kernel: [  120.423471] Modules linked in: bnep ecb ir_lirc_codec ir_xmp_decoder lirc_dev ir_mce_kbd_decoder ir_sharp_decoder ir_sanyo_decoder ir_sony_decoder ir_rc6_decoder ir_jvc_decoder ir_nec_decoder ir_rc5_decoder rc_rc6_mce joydev xpad btusb ff_memless bluetooth mceusb rc_core snd_hda_codec_hdmi arc4 nls_utf8 nls_cp437 vfat fat x86_pkg_temp_thermal intel_powerclamp intel_rapl coretemp nvidia(PO) kvm_intel wl(PO) iwlmvm snd_hda_codec_realtek snd_hda_codec_generic mac80211 kvm iTCO_wdt crct10dif_pclmul iTCO_vendor_support alienware_wmi crc32_pclmul ghash_clmulni_intel snd_hda_intel snd_hda_controller efi_pstore snd_hda_codec snd_hwdep psmouse aesni_intel snd_pcm aes_x86_64 snd_timer lrw gf128mul iwlwifi glue_helper ablk_helper cryptd efivars serio_raw cfg80211 pcspkr drm snd i2c_i801 soundcore rfkill i2c_core lpc_ich mfd_core 8250_fintek shpchp battery mei_me mei processor evdev fuse autofs4 ext4 crc16 mbcache jbd2 hid_logitech_dj usbhid hid sg sd_mod ahci libahci libata scsi_mod crc32c_intel xhci_pci xhci_hcd ehci_pci ehci_hcd r8169 mii usbcore usb_common fan thermal wmi video thermal_sys button
Aug 30 20:54:32 steamos kernel: [  120.423516] CPU: 2 PID: 51 Comm: kworker/2:1 Tainted: P        W  O   3.18.0-trunk+steamos2-amd64 #1 Debian 3.18.19-0+steamos2
Aug 30 20:54:32 steamos kernel: [  120.423517] Hardware name: Alienware ASM100/03V3TG, BIOS A04 07/14/2015
Aug 30 20:54:32 steamos kernel: [  120.423520] Workqueue: events presence_work_function [xpad]
Aug 30 20:54:32 steamos kernel: [  120.423521]  0000000000000000 0000000000000009 ffffffff81541f77 ffff8800dae4bb18
Aug 30 20:54:32 steamos kernel: [  120.423523]  ffffffff8106b117 ffff88020a3c7000 ffff8801fb0129e0 ffff880212eac5c8
Aug 30 20:54:32 steamos kernel: [  120.423524]  ffff8800daf2ac00 ffff880212f44890 ffffffff8106b17a ffffffff81736db8
Aug 30 20:54:32 steamos kernel: [  120.423526] Call Trace:
Aug 30 20:54:32 steamos kernel: [  120.423529]  [<ffffffff81541f77>] ? dump_stack+0x41/0x51
Aug 30 20:54:32 steamos kernel: [  120.423533]  [<ffffffff8106b117>] ? warn_slowpath_common+0x77/0x90
Aug 30 20:54:32 steamos kernel: [  120.423534]  [<ffffffff8106b17a>] ? warn_slowpath_fmt+0x4a/0x50
Aug 30 20:54:32 steamos kernel: [  120.423537]  [<ffffffff8122db17>] ? kernfs_path+0x47/0x60
Aug 30 20:54:32 steamos kernel: [  120.423538]  [<ffffffff8123112f>] ? sysfs_warn_dup+0x5f/0x70
Aug 30 20:54:32 steamos kernel: [  120.423540]  [<ffffffff812311be>] ? sysfs_create_dir_ns+0x7e/0x90
Aug 30 20:54:32 steamos kernel: [  120.423543]  [<ffffffff812cb738>] ? kobject_add_internal+0xc8/0x450
Aug 30 20:54:32 steamos kernel: [  120.423545]  [<ffffffff812d2fb6>] ? string.isra.7+0x36/0xe0
Aug 30 20:54:32 steamos kernel: [  120.423546]  [<ffffffff812cbf06>] ? kobject_add+0x66/0xb0
Aug 30 20:54:32 steamos kernel: [  120.423549]  [<ffffffff813c722b>] ? device_add+0x11b/0x6c0
Aug 30 20:54:32 steamos kernel: [  120.423551]  [<ffffffff813c79d8>] ? device_create_groups_vargs+0xe8/0x100
Aug 30 20:54:32 steamos kernel: [  120.423552]  [<ffffffff813c7a93>] ? device_create_with_groups+0x33/0x40
Aug 30 20:54:32 steamos kernel: [  120.423554]  [<ffffffff812d4b09>] ? snprintf+0x39/0x40
Aug 30 20:54:32 steamos kernel: [  120.423556]  [<ffffffff8140c28b>] ? led_classdev_register+0x3b/0x150
Aug 30 20:54:32 steamos kernel: [  120.423558]  [<ffffffffa05a17bf>] ? xpad_init_input+0x34f/0x3e0 [xpad]
Aug 30 20:54:32 steamos kernel: [  120.423560]  [<ffffffffa05a1e22>] ? presence_work_function+0x22/0x60 [xpad]
Aug 30 20:54:32 steamos kernel: [  120.423563]  [<ffffffff81082c5e>] ? process_one_work+0x14e/0x3f0
Aug 30 20:54:32 steamos kernel: [  120.423565]  [<ffffffff8108360b>] ? worker_thread+0x6b/0x4a0
Aug 30 20:54:32 steamos kernel: [  120.423567]  [<ffffffff810835a0>] ? rescuer_thread+0x290/0x290
Aug 30 20:54:32 steamos kernel: [  120.423569]  [<ffffffff81088363>] ? kthread+0xd3/0xf0
Aug 30 20:54:32 steamos kernel: [  120.423571]  [<ffffffff81088290>] ? kthread_create_on_node+0x180/0x180
Aug 30 20:54:32 steamos kernel: [  120.423573]  [<ffffffff81547c18>] ? ret_from_fork+0x58/0x90
Aug 30 20:54:32 steamos kernel: [  120.423575]  [<ffffffff81088290>] ? kthread_create_on_node+0x180/0x180
Aug 30 20:54:32 steamos kernel: [  120.423576] ---[ end trace 35dcd3fe75ffd824 ]---
Aug 30 20:54:32 steamos kernel: [  120.423577] ------------[ cut here ]------------
Aug 30 20:54:32 steamos kernel: [  120.423579] WARNING: CPU: 2 PID: 51 at /usr/src/packages/BUILD/linux-3.18.19/lib/kobject.c:240 kobject_add_internal+0x3d4/0x450()
Aug 30 20:54:32 steamos kernel: [  120.423580] kobject_add_internal failed for xpad0 with -EEXIST, don't try to register things with the same name in the same directory.
Aug 30 20:54:32 steamos kernel: [  120.423580] Modules linked in: bnep ecb ir_lirc_codec ir_xmp_decoder lirc_dev ir_mce_kbd_decoder ir_sharp_decoder ir_sanyo_decoder ir_sony_decoder ir_rc6_decoder ir_jvc_decoder ir_nec_decoder ir_rc5_decoder rc_rc6_mce joydev xpad btusb ff_memless bluetooth mceusb rc_core snd_hda_codec_hdmi arc4 nls_utf8 nls_cp437 vfat fat x86_pkg_temp_thermal intel_powerclamp intel_rapl coretemp nvidia(PO) kvm_intel wl(PO) iwlmvm snd_hda_codec_realtek snd_hda_codec_generic mac80211 kvm iTCO_wdt crct10dif_pclmul iTCO_vendor_support alienware_wmi crc32_pclmul ghash_clmulni_intel snd_hda_intel snd_hda_controller efi_pstore snd_hda_codec snd_hwdep psmouse aesni_intel snd_pcm aes_x86_64 snd_timer lrw gf128mul iwlwifi glue_helper ablk_helper cryptd efivars serio_raw cfg80211 pcspkr drm snd i2c_i801 soundcore rfkill i2c_core lpc_ich mfd_core 8250_fintek shpchp battery mei_me mei processor evdev fuse autofs4 ext4 crc16 mbcache jbd2 hid_logitech_dj usbhid hid sg sd_mod ahci libahci libata scsi_mod crc32c_intel xhci_pci xhci_hcd ehci_pci ehci_hcd r8169 mii usbcore usb_common fan thermal wmi video thermal_sys button
Aug 30 20:54:32 steamos kernel: [  120.423608] CPU: 2 PID: 51 Comm: kworker/2:1 Tainted: P        W  O   3.18.0-trunk+steamos2-amd64 #1 Debian 3.18.19-0+steamos2
Aug 30 20:54:32 steamos kernel: [  120.423608] Hardware name: Alienware ASM100/03V3TG, BIOS A04 07/14/2015
Aug 30 20:54:32 steamos kernel: [  120.423610] Workqueue: events presence_work_function [xpad]
Aug 30 20:54:32 steamos kernel: [  120.423611]  0000000000000000 0000000000000009 ffffffff81541f77 ffff8800dae4bb68
Aug 30 20:54:32 steamos kernel: [  120.423612]  ffffffff8106b117 ffff8800daf2ac10 00000000ffffffef ffff8800dbbfb5c0
Aug 30 20:54:32 steamos kernel: [  120.423614]  ffff8800daf2ac00 ffff880212f44890 ffffffff8106b17a ffffffff81751830
Aug 30 20:54:32 steamos kernel: [  120.423615] Call Trace:
Aug 30 20:54:32 steamos kernel: [  120.423616]  [<ffffffff81541f77>] ? dump_stack+0x41/0x51
Aug 30 20:54:32 steamos kernel: [  120.423618]  [<ffffffff8106b117>] ? warn_slowpath_common+0x77/0x90
Aug 30 20:54:32 steamos kernel: [  120.423620]  [<ffffffff8106b17a>] ? warn_slowpath_fmt+0x4a/0x50
Aug 30 20:54:32 steamos kernel: [  120.423621]  [<ffffffff812311be>] ? sysfs_create_dir_ns+0x7e/0x90
Aug 30 20:54:32 steamos kernel: [  120.423623]  [<ffffffff812cba44>] ? kobject_add_internal+0x3d4/0x450
Aug 30 20:54:32 steamos kernel: [  120.423625]  [<ffffffff812d2fb6>] ? string.isra.7+0x36/0xe0
Aug 30 20:54:32 steamos kernel: [  120.423626]  [<ffffffff812cbf06>] ? kobject_add+0x66/0xb0
Aug 30 20:54:32 steamos kernel: [  120.423628]  [<ffffffff813c722b>] ? device_add+0x11b/0x6c0
Aug 30 20:54:32 steamos kernel: [  120.423630]  [<ffffffff813c79d8>] ? device_create_groups_vargs+0xe8/0x100
Aug 30 20:54:32 steamos kernel: [  120.423631]  [<ffffffff813c7a93>] ? device_create_with_groups+0x33/0x40
Aug 30 20:54:32 steamos kernel: [  120.423632]  [<ffffffff812d4b09>] ? snprintf+0x39/0x40
Aug 30 20:54:32 steamos kernel: [  120.423634]  [<ffffffff8140c28b>] ? led_classdev_register+0x3b/0x150
Aug 30 20:54:32 steamos kernel: [  120.423636]  [<ffffffffa05a17bf>] ? xpad_init_input+0x34f/0x3e0 [xpad]
Aug 30 20:54:32 steamos kernel: [  120.423638]  [<ffffffffa05a1e22>] ? presence_work_function+0x22/0x60 [xpad]
Aug 30 20:54:32 steamos kernel: [  120.423640]  [<ffffffff81082c5e>] ? process_one_work+0x14e/0x3f0
Aug 30 20:54:32 steamos kernel: [  120.423642]  [<ffffffff8108360b>] ? worker_thread+0x6b/0x4a0
Aug 30 20:54:32 steamos kernel: [  120.423643]  [<ffffffff810835a0>] ? rescuer_thread+0x290/0x290
Aug 30 20:54:32 steamos kernel: [  120.423645]  [<ffffffff81088363>] ? kthread+0xd3/0xf0
Aug 30 20:54:32 steamos kernel: [  120.423646]  [<ffffffff81088290>] ? kthread_create_on_node+0x180/0x180
Aug 30 20:54:32 steamos kernel: [  120.423648]  [<ffffffff81547c18>] ? ret_from_fork+0x58/0x90
Aug 30 20:54:32 steamos kernel: [  120.423650]  [<ffffffff81088290>] ? kthread_create_on_node+0x180/0x180
Aug 30 20:54:32 steamos kernel: [  120.423650] ---[ end trace 35dcd3fe75ffd825 ]---
Aug 30 20:54:32 steamos kernel: [  120.423654] input input10: unable to init device   
</code>

**Comment by ekianjo** [comment] 2015-09-04 06:39
I confirm I have the same issue. I was playing Dirt:Showdown on SteamOS yesterday and when I tried to connect the second wireless Xbox360 pad, the whole system froze and I had to do a hard reset. That's disappointing.

**Comment by ProfessorKaos64** [comment] 2015-09-04 10:47
@jazz1138 , please use a [gist](https://gist.github.com/) for large output.

**Comment by HydrOptix** [comment] 2015-09-04 20:39
I have been having the same issue on the newest Brewmaster build. When connecting a wireless xbox 360 controller the OS freezes.

**Comment by lemonadecbc** [comment] 2015-09-05 10:45
Yes, this seems to be regression as xbox 360 controllers started to crash the kernel. Did not happen before upgrading Brewmaster v 2.44 with kernel 3.18+63+steamos6 .

syslog just before crash:
https://gist.github.com/lemonadecbc/0488808abecf375b9f52

**Comment by Tanren** [comment] 2015-09-15 09:54
Same problem for me in Brewmaster, it works in Alchemist.

**Comment by johnv-valve** [comment] 2015-09-17 19:03
Should be fixed in the latest brewmaster beta update. http://steamcommunity.com/groups/steamuniverse/discussions/1/523897653296978764/

**Closed by johnv-valve** 2015-09-17 19:03 UTC
