### ISSUE TITLE
Error message overlay 'Cannot read property 'estrength' of null' when a vlan or a bridge interface is configured in NetworkManager

### ISSUE THREAD

**Issue by ignisf** [ValveSoftware/SteamOS#1005] opened 2023-04-04 20:58 UTC
#### Your system information

* Steam client version: 1679680416
* SteamOS version: holo 3.4.6
* Opted into Steam client beta?: No 
* Opted into SteamOS beta?: No 
* Have you checked for updates in Settings > System?: Yes

#### Please describe your issue in as much detail as possible:

Added a vlan interface via `nmcli` by following https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/networking_guide/sec-configure_802_1q_vlan_tagging_using_the_command_line_tool_nmcli

Expected result: SteamOS should be able to connect to the Internet via the vlan tagged interface. No error messages should be displayed.

Actual result: SteamOS connects to the Internet, however the following error message overlay is displayed in place of the network connectivity indicator:

![Cannot read property 'estrength' of null](https://user-images.githubusercontent.com/1153188/229917752-792ade2f-7a32-4a57-bcec-4d5d3d493e79.png)

#### Steps for reproducing this issue:

1. Enter Desktop mode.
2. Run Konsole as root.
3. Follow https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/networking_guide/sec-configure_802_1q_vlan_tagging_using_the_command_line_tool_nmcli to add a vlan tagged interface via which to connect to Internet.
4. Return to Gaming mode.

Related issue: https://github.com/ValveSoftware/steam-for-linux/issues/9122

**Comment by kisak-valve** [comment] 2023-04-04 21:08
Hello @ignisf, this is an issue with the Steam client, not SteamOS as a platform, and you've already found the relevant issue report.

Closing as a duplicate of https://github.com/ValveSoftware/steam-for-linux/issues/9122.

**Closed by kisak-valve** 2023-04-04 21:08 UTC

**Comment by ignisf** [comment] 2023-04-04 21:26
Thank you and sorry for the duplicate.
