### ISSUE TITLE
Crash when viewing a community post in beta branch

### ISSUE THREAD

**Issue by blakejrobinson** [ValveSoftware/SteamOS#887] opened 2022-10-27 12:05 UTC
#### Your system information

* Steam client version: 1666733925
* SteamOS version: 3.3.2
* Opted into Steam client beta?: [Yes] 
* Opted into SteamOS beta?: [Yes] 
* Have you checked for updates in Settings > System?: [Yes]

#### Please describe your issue in as much detail as possible:
Viewing a community post causes the steam deck to either crash and restart, or hang and require a forced restart.

#### Steps for reproducing this issue:

1. Select a game from the home screen.
2. Tap to switch to the Community tab below the game's hero image.
3. Tap a community post that has text in it.
4. The steam deck will either hang on a black screen, or crash and restart itself.

A video of the issue can be seen at https://youtu.be/VmaxUr-H4tQ

**Comment by TTimo** [comment] 2022-10-27 13:27
Can't reproduce - I found this same post and it loaded fine.

**Comment by TTimo** [comment] 2022-10-27 14:36
Thanks, we're looking into it.

**Comment by blakejrobinson** [comment] 2022-11-04 16:01
> Thanks, we're looking into it.

Great! Did you manage to recreate this on your end? I've seen this issue confirmed by several others on the Steam Deck forums so am pretty sure it's not an isolated thing with my setup.

**Comment by blakejrobinson** [comment] 2022-11-10 22:56
This is fixed for me in latest client beta branch (version 1667952052)

**Comment by kisak-valve** [comment] 2022-11-10 23:21
Glad to hear it's working. Closing as fixed.

**Closed by kisak-valve** 2022-11-10 23:21 UTC
