### ISSUE TITLE
[ Audio Issue ] SteamOS does not remember Audio Config changes

### ISSUE THREAD

**Issue by ekianjo** [ValveSoftware/SteamOS#358] opened 2015-08-18 07:24 UTC
I have brewmaster installed and everything is working fine so far, apart from one issue. Right after installation the audio was not working. Since I have several HDMI ports on my GPU I suspected that it was not forwarding the audio from the appropriate port, and indeed that was the case. I could change that in the audio options and it was no issue. 

However, after a reboot, the sound is still missing and the configuration is not saved properly, basically. So every single time I need to change the sound parameter in the configuration to get the sound back.

Appreciate if you could fix that behavior.

**Comment by not83** [comment] 2015-08-18 07:28
I noticed fix bug but thought it was already reported

**Comment by sharkwouter** [comment] 2015-08-18 08:04
@not83 it has been, twice.

**Comment by ProfessorKaos64** [comment] 2015-08-19 17:36
Seems like a duplicate of #322

**Comment by GargGit** [comment] 2015-09-29 12:27
Same issue for me after last update (september 24). Lost audio settings after reboot.

**Comment by ProfessorKaos64** [comment] 2015-09-30 12:29
To all who hit this thread: I just updated this morning 0800 -500. As soon as I went into System > Audio, the sound came back. I rebooted and the option stuck. Fixed for me on an Nvidia GTX 770 over HDMI on a Gigabyte motherboard.

**Comment by johnv-valve** [comment] 2015-09-30 15:13
Yes, this should all be fixed with the latest beta client http://steamcommunity.com/groups/SteamClientBeta#announcements/detail/46517365035405897

**Closed by johnv-valve** 2015-09-30 15:13 UTC

**Comment by Schlesiger** [comment] 2015-10-01 03:39
I can confirm; sound settings now persist after reboot. I didn't even have to do a fresh install. Thanks!

**Comment by HanJiexi** [comment] 2015-11-26 07:37
My Cyber Steam Machine P had this problem when it arrived last week, even after upgrading to Steam client beta, so the issue doesn't seem to be fixed. The first option is analog output and the second was audio through NVIDIA HDMI, and it always wanted to go back to Analog Output after reboot.

The workaround I am using for now was to follow the instructions in this post from 2 years ago: http://steamcommunity.com/groups/steamuniverse/discussions/1/648814395855559064/#c648814395960547733

But what this did was completely remove the Analog Output option so that HDMI is always in the first place. So if I ever wanted to play in speakers, I wouldn't be able to use them without undoing that change in the PulseAudio configuration.

**Comment by not83** [comment] 2015-11-26 07:45
Have you updated to the latest SteamOS version as well? This was fixed for
everyone else

**Comment by HanJiexi** [comment] 2015-11-26 07:58
If by latest you mean beta, no. If by latest you mean latest stable, it was already up to date when it arrived (2.49 I think).

When I am with the machine again next week I can certainly try updating everything again, reverting the workaround, and testing to see if the problem still persists. I will post here again afterwards if I confirm that it does persist.

**Comment by HanJiexi** [comment] 2015-12-06 21:55
I reverted all of my system settings to what they were out-of-the-box and deleted the .pulse folders in /home/desktop and /home/steam, then rebooted. I checked and can once again confirm that, out-of-the-box, this issue was unresolved for me. It would forget my chosen audio output after every reboot.

However, after applying the fix in #433, I no longer experience this issue.
