### ISSUE TITLE
OLED not connecting to wifi/ i have to reboot to look for another network/ i can only use laptop(W11)/android hotspot

### ISSUE THREAD

**Issue by australok** [ValveSoftware/SteamOS#1291] opened 2023-12-06 11:51 UTC
#### Your system information

* Steam client version: 1701289036
* SteamOS version: 3.5.7
* Opted into Steam client beta?: i tested in both
* Opted into SteamOS beta?: No
* Have you checked for updates in Settings > System?: Yes

#### Please describe your issue in as much detail as possible:

as the title says, im unable to get direct wifi from my router sagemcom fast5670v2, i can only connect if i use my phone (android) or laptop (w11) as hotspot, as a plus, i tried hotspot with an iphone and doesn`t connect as well. When it doesnt connect i have to reboot because it seems to bug the wifi interface, also in desktop mode, it doesnt go beyond "configuring interface", or "no secrets were provided" ah, also running in wpa/wpa2-personal

i cant connect to any of the 2 bands, 2.4 and 5, with freq 160 deactivated, i tried EVERYTHING, factory reset, re installing Steam OS, everything except returning back the product and getting my money back because i`m stuck wih a 700 usd brick

this is the probe i did

https://linux-hardware.org/?probe=4704035dff

Describe what you _expected_ should happen and what _did_ happen.

expected: connect to my router like a NORMAL device

what did happen: unable to connect, forcing reboot in desktop mode with power button because it bugs the whole interface

#### Steps for reproducing this issue:

1. Buy a steam deck OLED 512 gb
2. Wait with all your hype
3. Frustrated and depressed because ur PSP can connect to ur sagemcom fast 5670 v2 but not the deck

![ad853370-be58-4ad0-acb8-c0ca0d62b189](https://github.com/ValveSoftware/SteamOS/assets/152485939/c13f0667-ab68-413d-8f51-69a5b075896a)

**Comment by RedAsKetchum** [comment] 2023-12-06 19:09
@lostgoat We are 21 days in and theres no word on this issue. Please say something.

**Comment by australok** [comment] 2023-12-07 18:37
@lostgoat hey man! what`s up? do u know anything about this? what should we do? request RMA? wait? please now i request, if possible, not a inmediate fix, but yes to tell me if i should sent my unit back to check if my device is ok or if this is a firmware (or anything related with the software), this is my main concern, idk what is wrong, if hardware of software, or both

**Comment by RedAsKetchum** [comment] 2023-12-07 21:58
> @lostgoat hey man! what`s up? do u know anything about this? what should we do? request RMA? wait? please now i request, if possible, not a inmediate fix, but yes to tell me if i should sent my unit back to check if my device is ok or if this is a firmware (or anything related with the software), this is my main concern, idk what is wrong, if hardware of software, or both

They dont care. They got our money and thats it. On top support takes 3-4 days between replies and they keep dancing around the RMA question. Try to RMA and thats it.

**Comment by australok** [comment] 2023-12-08 11:30
@EricS-Valve @jeffmvalve @cboyd-valve @cboyd-valve @lostgoat Good day! Can u please any of u tell us if this is a hardware related problem that needs a RMA, or a software issue that need us to keep waiting more? please let us know as soon as possible before the end of the 2 week gap to return the product

**Comment by Crysis85it** [comment] 2023-12-08 15:51
I have the same problem. There are several issues related to this with not a peep from Valve, that I know of. I'm returning this piece of crap. Better luck with next revision i guess...or not

**Comment by australok** [comment] 2023-12-10 00:38
Hey there! 

i add the [dmesg.log](https://pastebin.com/WuxLjmNT) of my issue where i show what happens when i try to connect to my home wifi, after the "no secrets were provided message" the network interface crashes forcing me to re-boot 2 times to fix the problem, wich causes very slow startup

@Nephyrin @JeffLeinbaugh @casieber @lostgoat 

have a great  night and Sunday!

**Comment by australok** [comment] 2023-12-10 12:33
updates?

**Comment by australok** [comment] 2023-12-11 10:53
still no updates from valve....

**Comment by australok** [comment] 2023-12-12 10:36
still no updates from valve....

**Comment by australok** [comment] 2023-12-12 10:36
still no update from them

**Comment by australok** [comment] 2023-12-13 16:48
update from support:

Hello. 

We apologize for all the inconvenience. 

I can see that we have determined that in order to resolve this issue, the unit has to be replaced.

I can confirm that the RMA has been initiated on the related ticket. 

If you have any further questions, please let us know - we will be happy to assist you.

Steam Support
Santiago H

**Comment by Crysis85it** [comment] 2023-12-13 20:37
This doesn't make any sense... si it is not a driver issue? Seems to be too widespread to be ah hardware fault. Plus I had the same problem and "workaround it" by disabling some nice things on my home network (like that nice 160Mhz band) Now it works but could be working better I think. Why don't they answer clearly???
Anyway let us know if you do RMA it if the problem persist on the same network

**Comment by Nephyrin** [comment] 2023-12-13 21:16
Closing as a duplicate of https://github.com/ValveSoftware/SteamOS/issues/1253

**Closed by Nephyrin** 2023-12-13 21:16 UTC

**Comment by australok** [comment] 2023-12-13 23:01
> Closing as a duplicate of #1253

Hey! it`s not duplicated if u read   #1253 he says:

Once I'm connected to a mobile hotspot I'm strangely allowed to connect to my router's network 2.4Ghz or 5Ghz. However, there are times when either coming back from sleep or turning the Sd back on shows you are no longer connected to the WIFI.


**i can`t connect to my router in this case**


"Turning off the 160mhz channel seems to fix the issue, but this nothing but a workaround that shouldnt be needed."


**in my router i can`t disable this option so its not a workaround for me**


with that said, it`s not the same problem at 100%, i don`t have any workaround and also disabling AX didnt do the job


thanks!

**Comment by Black-Seraph** [comment] 2024-03-23 18:52
Try this:

sudo mv /etc/NetworkManager/conf.d/wifi_backend.conf /etc/NetworkManager/conf.d/wifi_backend.conf.bak

Then reboot.
