### ISSUE TITLE
Fatal error loop

### ISSUE THREAD

**Issue by Rav8es** [ValveSoftware/SteamOS#674] opened 2019-04-09 01:16 UTC
#### Your system information

* Steam client version: N/A
* SteamOS version: 2.184
* Opted into Steam client beta?: N/A
* Opted into SteamOS beta?: Yes
* Have you checked for updates in Settings > System?: Yes

#### Please describe your issue in as much detail as possible:
1.Installed Steam OS 
2.Booted up to desktop
3. Steam updates, kernel installs.
4. Part clone imitated, finishes. Reboots.
5. Grub loads, steam logo appears on startup, hardware configuration loads
6. many colors on screen, black screen.
7. Reboots. 
8. Repeat step 5 (without hardware configuration showing), load TTY (alt ctrl f2), install steam os beta repo. Reboot.
9. Step 5-6 repeated. Fatal error screen now shows.
10. Reboots and cycles steps 8-10 over and over.

#### Steps for reproducing this issue:

1. Boot up computer, select SteamOS in grub.

######
Performed actions in thread below:

User rav8es on SteamOS discussion: https://steamcommunity.com/groups/steamuniverse/discussions/1/1848072002749887378/?ctp=2

[package-list.log](https://github.com/ValveSoftware/SteamOS/files/3056781/package-list.log)
[upgrade-diagnostic.log](https://github.com/ValveSoftware/SteamOS/files/3056782/upgrade-diagnostic.log)

System specs:
AMD 8350
Sapphire Vega 64
ASUS 990fx

**Comment by fledermaus** [comment] 2019-04-09 12:16
Thanks. I think this might be the same as the other AMD issue, but the system is hardwired to try and build the NVIDIA driver, hence the delay between reboots.

Can you attach /var/log/Xorg.0.log as well?

**Comment by Rav8es** [comment] 2019-04-09 22:34
> 
> 
> Thanks. I think this might be the same as the other AMD issue, but the system is hardwired to try and build the NVIDIA driver, hence the delay between reboots.
> 
> Can you attach /var/log/Xorg.0.log as well?

Sure thing. See attached.

[Xorg.0.log](https://github.com/ValveSoftware/SteamOS/files/3061229/Xorg.0.log)

**Comment by fledermaus** [comment] 2019-04-10 20:23
Interesting. This is _not_ the same as the other AMD GPU related bug. Have you got a fair bit of Xorg custom configuration on your system?

**Comment by Rav8es** [comment] 2019-04-10 20:25
I have not performed any customizations on my system in regards to Xorg, or any other settings.

**Comment by fledermaus** [comment] 2019-04-10 21:18
Ok, thanks.

**Comment by fledermaus** [comment] 2019-04-10 21:21
What input peripherals have you got attached? Looks like your bug might be a problem in evdev.

**Comment by Rav8es** [comment] 2019-04-10 21:27
Steel Series keyboard via USB
Steel series mouse via USB
Steel series arctis 7 headphones via USB
Samsung 1440P monitor via display port to vega 64 pci 16

**Comment by fledermaus** [comment] 2019-04-10 22:25
Huh. Well this looks very odd then:
`
  [    12.297] (II) XINPUT: Adding extended input device "SteelSeries  SteelSeries Arctis 7" (type: KEYBOARD, id 8)
  [    12.297] (**) Option "xkb_rules" "evdev"
  [    12.297] (**) Option "xkb_model" "pc105"
  [    12.297] (**) Option "xkb_layout" "us"
  [    12.298] (EE) BUG: triggered 'if (axnum >= dev->valuator->numAxes)'
`

I'm not really familiar with the guts of evdev and frankly this sounds weird to me even as I type it, but … if you unplug the Arctis 7 does the problem go away? Or is the xorg log at least significantly different?

**Comment by Rav8es** [comment] 2019-04-10 22:51
New log without arctis 7 plugged in:

[Xorg.0[1].log](https://github.com/ValveSoftware/SteamOS/files/3066164/Xorg.0.1.log)

Same problem.

**Comment by fledermaus** [comment] 2019-04-11 14:23
This might be a case of requiring a newer amdgpu driver - looks like you're ending up in the modesetting driver as the amdgpu driver in brewmaster does not recognise the card. I think. More news when I have it.

**Comment by fledermaus** [comment] 2019-04-11 15:19
Ok, updating the driver _should_ fix this but will also require a fix for issue #673 to be of any use.

**Comment by Rav8es** [comment] 2019-04-11 15:33
Ok are you stating the 2 issues will be combined on the same hypothetical update, and the pushed to brewmaster beta repo?

**Comment by fledermaus** [comment] 2019-04-11 22:50
That's the most likely outcome, given what I know about the bug so far.

**Comment by fledermaus** [comment] 2019-04-12 18:48
Released a fix, wil close bug when/if confirmed.

**Comment by Rav8es** [comment] 2019-04-12 22:37
Bug confirmed fixed. Thank you.

**Comment by kisak-valve** [comment] 2019-04-12 22:49
Thanks for retesting. Closing per the last comment.

**Closed by kisak-valve** 2019-04-12 22:49 UTC
