### ISSUE TITLE
SDR Games with HDR enabled appear to have too high contrast/brightness

### ISSUE THREAD

**Issue by anthr76** [ValveSoftware/SteamOS#1421] opened 2024-03-12 23:49 UTC
#### Your system information

* Steam client version: 1709846872
* SteamOS version: (Custom build based off of Jovian-NixOS)
* Opted into Steam client beta?: No (same issue in beta)
* Opted into SteamOS beta?: No
* Have you checked for updates in Settings > System?: Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen.

#### Steps for reproducing this issue:

1. Enable HDR
2. Play a SDR Game
3. Observe bright whites to be over saturated and hard to read/look at

 
I have an issue where when I play SDR games with HDR enabled in the display settings the colors/gamma looks washed out. If I disable HDR in the display settings in the steam UI the picture looks perfect. Curiously the TV reports HDR as off when playing SDR games while HDR is enabled in settings. When in the steam menus or in HDR games the tv reports HDR signal. HDR games look fine as well. It appears a partial HDR signal is being sent by steam/gamescope when SDR games are being played. Is anyone aware of a upstream issue? I'm not even sure where to even report this between gamescope/steamos/amdgpu/mesa.

Kernel: 6.8.0-rc7
Mesa: steamos-24.1.2/24.1.0
Gamescope: 3.14.2-unstable-2024-02-28

**Comment by kisak-valve** [comment] 2024-03-13 00:49
Hello @anthr76, this reads like a duplicate of #1227. Closing in favor of the older issue report.

**Closed by kisak-valve** 2024-03-13 00:49 UTC

**Comment by anthr76** [comment] 2024-03-13 01:15
Thanks for the quick response @kisak-valve I'm not positive this is the same issue i;e https://github.com/ValveSoftware/SteamOS/issues/1227#issuecomment-1836946641

But I will post the OP there anyway
