### ISSUE TITLE
SD card not being automatically mounted after updating to 3.5.5

### ISSUE THREAD

**Issue by CapCreeperGR** [ValveSoftware/SteamOS#1208] opened 2023-11-17 15:27 UTC
#### Your system information

* Steam client version: 1700160213
* SteamOS version:  3.5.5
* Opted into Steam client beta?: No
* Opted into SteamOS beta?: No
* Have you checked for updates in Settings > System?: Yes

#### Please describe your issue in as much detail as possible:
I just updated my steam deck to SteamOS 3.5.5 and when the update finished and got back to gaming mode I saw that none of my games appeared as installed. I went into desktop mode to see what the problem was and when I clicked on the SD card in the file explorer it told me that it was trying to create a 'none' directory but couldn't. After that I opened the KDE partition manager to see if my SD card was being read at all there and it showed me that there was no mount point for the card. I tried mounting it manually through the console with the following steps and it works properly but it still doesn't auto-mount after a reboot:
- sudo mkdir /run/media/mmcblk0p1
- sudo mount /dev/mmcblk0p1 /run/media/mmcblk0p1

#### Steps for reproducing this issue:

1. Have an SD card inserted into the steam deck
2. Update SteamOS to 3.5.5
3. Wait for the update to finish

**Comment by bertogg** [comment] 2023-11-17 15:31
Can you run these commands in a terminal (as root)?

```
# lsblk -d /dev/mmcblk*
# blkid /dev/mmcblk*
```

**Comment by CapCreeperGR** [comment] 2023-11-17 15:58
```
# lsblk -d /dev/mmcblk*
mmcblk0 179:0 0 477.5G 0 disk
mmcblk0p1 179:1 0 477.5G 0 part
# blkid /dev/mmcblk*
(shows nothing)
```

**Comment by bertogg** [comment] 2023-11-17 16:13
Did you run those as root (or with `sudo lsblk ...` etc)? You have a partition there but `blkid` shows no partition table...

**Comment by CapCreeperGR** [comment] 2023-11-17 16:23
sorry my bad, I thought I did
```
# lsblk -d /dev/mmcblk*
mmcblk0 179:0 0 477.5G 0 disk
mmcblk0p1 179:1 0 477.5G 0 part
# blkid /dev/mmcblk*
/dev/mmcblk0: PTUID="(a uuid that's too long to copy)" PTTYPE="gpt"
/dev/mmcblk0p1: UUID="(another uuid)" BLOCK_SIZE="4096" TYPE="ext4" PARTLABEL="primary" PARTUUID="(another uuid)"
```

**Comment by bertogg** [comment] 2023-11-17 16:42
Ok, that looks correct, this should be mounted automatically without you having to create any directory, can you run these and see if they show any error? (again, they need to be run as root or with `sudo`)

```
# e2fsck -n -f /dev/mmcblk0p1
# journalctl -b | grep -E 'mmcblk|steamos-automount'
```

**Comment by CapCreeperGR** [comment] 2023-11-17 16:47
```
# e2fsck -n -f /dev/mmcblk0p1

e2fsck 1.47.0 (5-Feb-2023)
Pass 1: Checking inodes, blocks, and sizes
Inode 24512986 extent tree (at level 1) could be narrower.  Optimize? no

Inode 24777385 extent tree (at level 2) could be narrower.  Optimize? no

Inode 24777388 extent tree (at level 2) could be narrower.  Optimize? no

Inode 24777389 extent tree (at level 2) could be narrower.  Optimize? no

Inode 24777391 extent tree (at level 2) could be narrower.  Optimize? no

Inode 24777410 extent tree (at level 1) could be narrower.  Optimize? no

Inode 24777416 extent tree (at level 1) could be narrower.  Optimize? no

Inode 24777419 extent tree (at level 2) could be narrower.  Optimize? no

Inode 24905694 extent tree (at level 2) could be narrower.  Optimize? no

Inode 24905704 extent tree (at level 1) could be narrower.  Optimize? no

Inode 24905725 extent tree (at level 1) could be narrower.  Optimize? no

Inode 25175823 extent tree (at level 2) could be narrower.  Optimize? no

Inode 25690144 extent tree (at level 1) could be narrower.  Optimize? no

Inode 25690146 extent tree (at level 1) could be narrower.  Optimize? no

Inode 25690167 extent tree (at level 1) could be narrower.  Optimize? no

Inode 25690170 extent tree (at level 1) could be narrower.  Optimize? no

Pass 2: Checking directory structure
Pass 3: Checking directory connectivity
Pass 4: Checking reference counts
Pass 5: Checking group summary information
/dev/mmcblk0p1: 161428/31293440 files (0.4% non-contiguous), 55047898/125173248 blocks

# journalctl -b | grep -E 'mmcblk|steamos-automount'

Nov 17 18:18:38 LightningDeck kernel: mmcblk0: mmc0:59b4 EF8S5 478 GiB 
Nov 17 18:18:38 LightningDeck kernel:  mmcblk0: p1
Nov 17 18:18:39 LightningDeck systemd[1]: Created slice Slice /system/steamos-automount.
Nov 17 18:18:41 LightningDeck systemd[1]: Starting Mount removable drive mmcblk0p1 and notify Steam...
Nov 17 18:18:41 LightningDeck steamos-automount.sh[726]: e2fsck 1.47.0 (5-Feb-2023)
Nov 17 18:18:41 LightningDeck steamos-automount.sh[726]: /dev/mmcblk0p1: clean, 161428/31293440 files, 55047898/125173248 blocks
Nov 17 18:18:41 LightningDeck busctl[732]: Call failed: Error creating directory `none' to be used for mounting /dev/mmcblk0p1: Read-only file system
Nov 17 18:18:41 LightningDeck steamos-automount.sh[556]: Could not send steam URL steam://system/devicemountresult/mmcblk0p1/2 (steam://system/devicemountresult/%6d%6d%63%62%6c%6b%30%70%31%2f%32) -- steam not running
Nov 17 18:18:41 LightningDeck steamos-automount.sh[556]: Error mounting /dev/mmcblk0p1 (status = 1)
Nov 17 18:18:41 LightningDeck systemd[1]: steamos-automount@mmcblk0p1.service: Main process exited, code=exited, status=1/FAILURE
Nov 17 18:18:41 LightningDeck systemd[1]: steamos-automount@mmcblk0p1.service: Failed with result 'exit-code'.
Nov 17 18:18:41 LightningDeck systemd[1]: Failed to start Mount removable drive mmcblk0p1 and notify Steam.
Nov 17 18:20:32 LightningDeck dbus-daemon[546]: [system] Activating via systemd: service name='org.freedesktop.home1' unit='dbus-org.freedesktop.home1.service' requested by ':1.129' (uid=0 pid=4070 comm="sudo lsblk -d /dev/mmcblk0 /dev/mmcblk0p1")
Nov 17 18:20:37 LightningDeck sudo[4070]:     deck : TTY=pts/1 ; PWD=/home/deck ; USER=root ; COMMAND=/usr/bin/lsblk -d /dev/mmcblk0 /dev/mmcblk0p1
Nov 17 18:20:50 LightningDeck dbus-daemon[546]: [system] Activating via systemd: service name='org.freedesktop.home1' unit='dbus-org.freedesktop.home1.service' requested by ':1.130' (uid=0 pid=4106 comm="sudo blkid /dev/mmcblk0 /dev/mmcblk0p1")
Nov 17 18:20:50 LightningDeck sudo[4106]:     deck : TTY=pts/1 ; PWD=/home/deck ; USER=root ; COMMAND=/usr/bin/blkid /dev/mmcblk0 /dev/mmcblk0p1
Nov 17 18:44:52 LightningDeck dbus-daemon[546]: [system] Activating via systemd: service name='org.freedesktop.home1' unit='dbus-org.freedesktop.home1.service' requested by ':1.135' (uid=0 pid=4367 comm="sudo e2fsck -n -f /dev/mmcblk0p1")
Nov 17 18:44:54 LightningDeck sudo[4367]:     deck : TTY=pts/1 ; PWD=/home/deck ; USER=root ; COMMAND=/usr/bin/e2fsck -n -f /dev/mmcblk0p1
```

**Comment by CapCreeperGR** [comment] 2023-11-17 17:05
I am pretty sure I haven't modified it. This only started happening today after updating to 3.5.5
Here's my fstab file
```
# Static information about the filesystems.
# See fstab(5) for details.

# <file system> <dir> <type> <options> <dump> <pass>
# SteamOS partitions
#/dev/disk/by-partsets/self/rootfs /       ext4    defaults                0       1
#/dev/disk/by-partsets/self/var    /var    ext4    defaults                0       2
/dev/disk/by-partsets/self/efi      /efi    vfat   nofail,umask=0077,x-systemd.automount,x-systemd.idle-timeout=1min   0 2
/dev/disk/by-partsets/shared/esp    /esp    vfat   nofail,umask=0077,x-systemd.automount,x-systemd.idle-timeout=1min   0 2
/dev/disk/by-partsets/shared/home   /home   ext4   nofail,x-systemd.growfs                                             0 2
/dev/mmcblk0p1                      none    ext4   defaults  
```

**Comment by bertogg** [comment] 2023-11-17 17:15
> `/dev/mmcblk0p1                      none    ext4   defaults`

I don't know where this line came from, I assume you have a `/var/lib/overlays/etc/upper/fstab` file, can you confirm that?

**After** checking that, you can edit `/etc/fstab` and comment-out that line (putting a `#` at the beginning). Then you should be able to mount your sd card again while I investigate where that line could have come from.

**Comment by CapCreeperGR** [comment] 2023-11-17 17:19
the SD card is in both fstab files. Do I go on and put the hashtag in /etc/fstab now or no?

**Comment by bertogg** [comment] 2023-11-17 17:22
Yes, you can edit `/etc/fstab` and put the hash symbol. After that you should be able to use your sdcard normally.

Someone modified that file before, I'll investigate possible causes.

**Comment by CapCreeperGR** [comment] 2023-11-17 17:25
Yep works great now, thanks!

**Comment by Ponjen** [comment] 2023-11-17 18:11
I can confirm this worked for me as well, however it introduced a new problem. For some reason, my microSD lost some storage after fixing it (editing fstab). Just did the math by looking at my actual storage and adding up what's on there. My card's capacity is 461.89 GiB. I should have around 122 GiB of storage left (which is what I had before). I instead have around 113 GiB left. So something took 8.59 GiB of storage. KDE Partition Manager and File Light show nothing out of the ordinary. They both show what my remaining size SHOULD be. Steam and Dolphin show the smaller size. Steam also showed a second Steam Library for my microSD. It listed my internal, then my microSD, but then a third one simply called "External Device." The size of it matched my  missing storage. I removed "External Device" from the Steam storage settings, hoping it would return it. It did not.

**Comment by bertogg** [comment] 2023-11-18 00:29
> the fstab file was the issue for 3.5.5. How it got edited is beyond me. Possibly there's a plugin that uses it?

I'm suspecting of the KDE Partition Manager, do you remember if you used it?

Example: if I open it -> select mmcblk0 -> right click -> select "Edit mount point" -> press OK then fstab is overwritten and it looks exactly like what @CapCreeperGR pasted.

It could have been with different steps, or with some other app that uses the same library.

Either way this will be handled asap because I'm sure there are more users with the same problem.

Thanks for reporting the problem and providing the details!

**Comment by Ponjen** [comment] 2023-11-18 00:40
I never edited the mount point in KDE Partition Manager until the issue with 3.5.5. Only time I used KDE Partition Manager prior was to format or adjust partitions with other microSD cards. But I never touched the mount points.

I was thinking it was maybe when I disabled case folding in my Oblivion folder (so mods would work properly), but none of those commands messed with fstab. I don't know if Cryo Utilities messes with it. I uninstalled it months ago.

**Comment by bertogg** [comment] 2023-11-18 00:47
Ok, I suspect that there are several possible ways to end up in a situation like this. We'll work on a solution, thanks again.

**Comment by Ponjen** [comment] 2023-11-18 15:00
Reinstalled CryoUtilities (Midnight Suns regularly crashes without it). No issues with the microSD.

**Comment by ffrasisti** [comment] 2023-11-28 05:20
My sd card is mounting but to a rare path that is not the usual mlbck01 one

**Comment by ffrasisti** [comment] 2023-11-28 11:09
I tried using kde partition manager to change the mount point but i cant point it to the original, im guessing its because of the symlink put in place? Ill just leave it as is if its intended. Though i cant imagine why they would change itEl 28 nov. 2023 7:54, Alberto Garcia ***@***.***> escribió:

My sd card is mounting but to a rare path that is not the usual mlbck01 one

This is normal, but the old path is still reachable for compatibility.

**Comment by bertogg** [comment] 2023-11-28 12:13
> I tried using kde partition manager to change the mount point but i cant point it to the original

To be clear: I don't recommend that you use the KDE partition manager to edit the mount point of the SD card. The `/etc/fstab` file should not contain any line with `/dev/mmcblk0p1`. If you have one I suggest that you remove it (or comment it out with the `#` symbol).

**Comment by RedAsKetchum** [comment] 2023-12-05 04:22
> > I tried using kde partition manager to change the mount point but i cant point it to the original
> 
> To be clear: I don't recommend that you use the KDE partition manager to edit the mount point of the SD card. The `/etc/fstab` file should not contain any line with `/dev/mmcblk0p1`. If you have one I suggest that you remove it (or comment it out with the `#` symbol).

What if my micro sd suddenly doesnt mount either, but I also dont have an mmcblk0p1 entry on my fstab file?

**Comment by bertogg** [comment] 2023-12-05 12:21
> What if my micro sd suddenly doesnt mount either, but I also dont have an mmcblk0p1 entry on my fstab file?

For people that are having problems mounting their SD cards, please run the following commands and paste their output:
```
# sudo lsblk -d /dev/mmcblk*
# sudo blkid /dev/mmcblk*
# sudo e2fsck -n -f /dev/mmcblk0p1
# grep mmcblk /etc/fstab
# sudo journalctl -b | grep -E 'mmcblk|steamos-automount'
```

**Comment by bertogg** [comment] 2023-12-20 17:11
@KosmicAnosmic that log looks correct, you don't see the sd card at all? Neither in game nor in desktop mode using the file browser?

**Comment by sirilinski** [comment] 2023-12-21 21:23
![image](https://github.com/ValveSoftware/SteamOS/assets/154559108/0f8ac1f0-4fbe-4045-b136-8536890b3ea7)

so... i got this, pretty sure that's not how it's supposed to look, but i'm not very familiar with linux and i'm having this exact issue with my microsds... am i doing the process wrong? i already set a password and copy pasted the exact commands from here adding "sudo"

**Comment by kisak-valve** [comment] 2023-12-21 21:57
Hello @sirilinski, bash is reading `#` in that context as everything after the `#` is a comment and ignored, so it's as if you ran `sudo` with nothing else, and it's responding by giving you some usage examples.

**Comment by bertogg** [comment] 2023-12-22 11:27
Yeah the `#` symbol is the prompt and is only used to indicate where the command begins, you should not actually type `#` when you enter the command.

**Comment by MezzyMart** [comment] 2023-12-23 02:28
> Yes, you can edit `/etc/fstab` and put the hash symbol. After that you should be able to use your sdcard normally.
> 
> Someone modified that file before, I'll investigate possible causes.

This is the only thing that's worked for me! Thank you!!

**Comment by Retragrade** [comment] 2023-12-30 16:30
> > What if my micro sd suddenly doesnt mount either, but I also dont have an mmcblk0p1 entry on my fstab file?
> 
> For people that are having problems mounting their SD cards, please run the following commands and paste their output:
> 
> ```
> # sudo lsblk -d /dev/mmcblk*
> # sudo blkid /dev/mmcblk*
> # sudo e2fsck -n -f /dev/mmcblk0p1
> # grep mmcblk /etc/fstab
> # sudo journalctl -b | grep -E 'mmcblk|steamos-automount'
> ```

(1)(deck@steamdeckGJ ~)$ sudo journalctl -b | grep -E 'mmcblk|steamos-automount'
Dec 29 18:52:55 steamdeckGJ kernel: mmcblk0: mmc0:aaaa SN01T 954 GiB
Dec 29 18:52:55 steamdeckGJ kernel: mmcblk0: p1
Dec 29 18:52:55 steamdeckGJ systemd[1]: Created slice Slice /system/steamos-automount.
Dec 29 18:52:57 steamdeckGJ systemd[1]: Starting Mount External Drive mmcblk0...
Dec 29 18:52:57 steamdeckGJ systemd[1]: Starting Mount External Drive mmcblk0...
Dec 29 18:52:57 steamdeckGJ systemd[1]: Starting Mount removable drive mmcblk0p1 and notify steam...
Dec 29 18:52:57 steamdeckGJ steamos-automount.sh[618]: var/run/jupiter-automount-mmcblk0p1.lock is active: ignoring action add 
Dec 29 18:52:57 steamdeckGJ steamos-automount.sh[621]: var/run/jupiter-automount-sda1.lock is active: ignoring action add
Dec 29 18:52:55 steamdeckGJ systemd[1]: steamos-automount@mmcblk0p1.service: Main process exited, code=exited, status=1/FAILURE
Dec 29 18:52:55 steamdeckGJ systemd[1]: steamos-automount@mmcblk0p1.service: Failed with result 'exit-code'.
Dec 29 18:52:58 steamdeckGJ systemd[1]: Failed to start Mount removable drive mmcblk0p1 and notify steam.
Dec 29 18:52:58 steamdeckGJ systemd[1]: steamos-automount@sda1.service: Main process exited, code=exited, status=1/FAILURE.
Dec 29 18:52:58 steamdeckGJ systemd[1]: steamos-automount@sda1.service: Failed with result 'exit-code'.
Dec 29 18:52:58 steamdeckGJ automount.sh[593]: Error mounting /dev/mmcblk01p: SteamOS does ext4 for us!
Dec 29 18:52:58 steamdeckGJ systemd[1]: external-drive-mount@mmcblk01p.service: Main process exited, code=exited, status=2/INVALIDARGUMENT.
Dec 29 18:52:58 steamdeckGJ systemd[1]: external-drive-mount@mmcblk01p.service: Failed with result 'exit-code'.
Dec 29 18:52:58 steamdeckGJ automount.sh[592]: Error mounting /dev/mmcblk0: unsupported fstype: - {
Dec 29 18:52:58 steamdeckGJ automount.sh[592]:   "path": "/dev/mmcblk0",
Dec 29 18:52:58 steamdeckGJ systemd[1]: Failed to start Mount External Drive on mmcblk0p1.
Dec 29 18:52:58 steamdeckGJ systemd[1]: external-drive-mount@mmcblk0.service: Main process exited, code=exited, status=2/INVALIDARGUMENT.
Dec 29 18:52:58 steamdeckGJ systemd[1]: external-drive-mount@mmcblk0.service: Failed with result 'exit-code'.
Dec 29 18:52:58 steamdeckGJ systemd[1]: Failed to start Mount External Drive on mmcblk0.
Dec 29 19:04:01 steamdeckGJ kernel: EXT4-fs (mmcblk0p1): Using encoding defined by superblock: utf8-12.1.0 with flags 0x0
Dec 29 19:04:01 steamdeckGJ kernel: EXT4-fs (mmcblk0p1): mounted filesystem with ordered data mode. Quota mode: none.
Dec 29 19:04:01 steamdeckGJ udisksd[1592]: Mounted /dev/mccblk0p1 at /run/media/deck/7fb68156-7764-4eae-a438-ff6516a22ed5 on behalf of uid 1000
Dec 29 20:31:52 steamdeckGJ dbus-daemon[598]: [system] Activating via systemd: service name='org.freedesktop.home1' unit='dbus-org.freedesktop.home1.service' requested by ':1.166' (uid=0 pid=7503 comm="sudo e2fsck -n -f /dev/mmcblk0p1")
Dec 29 20:32:21 steamdeckGJ sudo[7503]: deck : TTY=pts/1 ; PWD=/home/deck ; USER=root ; COMMAND=/usr/bin/e2fsck -n -f /dev/mmcblk0p1
Dec 29 20:35:14 steamdeckGJ dbus-daemon[598]: [system] Activating via systemd: service name='org.freedesktop.home1' unit='dbus-org.freedesktop.home1.service' requested by ':1.167' (uid=0 pid=7572 comm="sudo grep mmcblk /etc/fstab")
Dec 29 20:35:14 steamdeckGJ sudo[7572]: deck : TTY=pts/1 ; PWD=/home/deck ; USER=root ; COMMAND=/usr/bin/grep mmcblk /etc/fstab
Dec 29 20:38:51 steamdeckGJ dbus-daemon[598]: [system] Activating via systemd: service name='org.freedesktop.home1' unit='dbus-org.freedesktop.home1.service' requested by ':1.168' (uid=0 pid=7747 comm="sudo lsblk -d /dev/mmcblk0 /dev/mmcblk0p1")
Dec 29 20:39:21 steamdeckGJ sudo[7747]: deck : TTY=pts/1 ; PWD=/home/deck ; USER=root ; COMMAND=/usr/bin/lsblk -d /dev/mmcblk0 /dev/mmcblk0p1
Dec 29 20:40:28 steamdeckGJ dbus-daemon[598]: [system] Activating via systemd: service name='org.freedesktop.home1' unit='dbus-org.freedesktop.home1.service' requested by ':1.169' (uid=0 pid=7772 comm="sudo blkid /dev/mmcblk0 /dev/mmcblk0p1")
Dec 29 20:40:28 steamdeckGJ sudo[7772]: deck : TTY=pts/1 ; PWD=/home/deck ; USER=root ; COMMAND=/usr/bin/blkid /dev/mmcblk0 /dev/mmcblk0p1
(deck@steamdeckGJ ~)$

**Comment by bertogg** [comment] 2024-01-09 11:19
Hello, this has been fixed in the preview channel.

I just tested it with SteamOS 3.5.13 (build ID, 20240104.1), but the fix is also included in earlier versions.

**Comment by bertogg** [comment] 2024-01-09 16:54
@Retragrade

You are using an additional, third-party auto-mount script (https://github.com/scawp/Steam-Deck.Mount-External-Drive or a variation of that one) so there might be interactions. Try disabling it / removing it and see if you still have problems.

```
Dec 29 18:52:58 steamdeckGJ automount.sh[593]: Error mounting /dev/mmcblk01p: SteamOS does ext4 for us!
Dec 29 18:52:58 steamdeckGJ systemd[1]: [external-drive-mount@mmcblk01p.service](mailto:external-drive-mount@mmcblk01p.service): Main process exited, code=exited, status=2/INVALIDARGUMENT.
```

**Comment by piperojasjaimes** [comment] 2024-01-11 08:30
(1)(deck@steamdeck ~)$ sudo lsblk -d /dev/mmcblk*
[sudo] password for deck: 
Sorry, try again.
[sudo] password for deck: 
NAME      MAJ:MIN RM   SIZE RO TYPE MOUNTPOINTS
mmcblk0   179:0    0 477.5G  0 disk 
mmcblk0p1 179:1    0 477.5G  0 part /run/media/deck/1aa748c3-177d-4b03-8fee-496e65bb203d
(deck@steamdeck ~)$ sudo blkid /dev/mmcblk*
/dev/mmcblk0: PTUUID="1c4eb71c-0a39-4590-8cb9-6c245ce8199b" PTTYPE="gpt"
/dev/mmcblk0p1: UUID="1aa748c3-177d-4b03-8fee-496e65bb203d" UUID_SUB="be50d599-2459-4a45-b34d-9cdfe54ed618" BLOCK_SIZE="4096" TYPE="btrfs" PARTLABEL="primary" PARTUUID="ecbcb314-1b53-4011-8580-28a18d1133b9"
(deck@steamdeck ~)$ sudo e2fsck -n -f /dev/mmcblk0p1
e2fsck 1.47.0 (5-Feb-2023)
Warning!  /dev/mmcblk0p1 is in use.
ext2fs_open2: Bad magic number in super-block
e2fsck: Superblock invalid, trying backup blocks...
e2fsck: Bad magic number in super-block while trying to open /dev/mmcblk0p1

The superblock could not be read or does not describe a valid ext2/ext3/ext4
filesystem.  If the device is valid and it really contains an ext2/ext3/ext4
filesystem (and not swap or ufs or something else), then the superblock
is corrupt, and you might try running e2fsck with an alternate superblock:
    e2fsck -b 8193 <device>
 or
    e2fsck -b 32768 <device>

/dev/mmcblk0p1 contains a btrfs file system
(8)(deck@steamdeck ~)$ grep mmcblk /etc/fstab
(1)(deck@steamdeck ~)$ sudo journalctl -b | grep -E 'mmcblk|steamos-automount'
Jan 11 03:15:27 steamdeck kernel: mmcblk0: mmc0:59b4 GF8S5 478 GiB 
Jan 11 03:15:27 steamdeck kernel:  mmcblk0: p1
Jan 11 03:15:27 steamdeck kernel: BTRFS: device fsid 1aa748c3-177d-4b03-8fee-496e65bb203d devid 1 transid 4676 /dev/mmcblk0p1 scanned by (udev-worker) (406)
Jan 11 03:15:28 steamdeck systemd[1]: Created slice Slice /system/steamos-automount.
Jan 11 03:15:29 steamdeck systemd[1]: Starting Mount removable drive mmcblk0p1 and notify Steam...
Jan 11 03:15:30 steamdeck steamos-automount.sh[572]: Error mounting /dev/mmcblk0p1: wrong fstype: btrfs - {
Jan 11 03:15:30 steamdeck steamos-automount.sh[572]:   "path": "/dev/mmcblk0p1",
Jan 11 03:15:30 steamdeck steamos-automount.sh[572]:   "label": null,
Jan 11 03:15:30 steamdeck steamos-automount.sh[572]:   "fstype": "btrfs"
Jan 11 03:15:30 steamdeck steamos-automount.sh[572]: }
Jan 11 03:15:30 steamdeck systemd[1]: steamos-automount@mmcblk0p1.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jan 11 03:15:30 steamdeck systemd[1]: steamos-automount@mmcblk0p1.service: Failed with result 'exit-code'.
Jan 11 03:15:30 steamdeck systemd[1]: Failed to start Mount removable drive mmcblk0p1 and notify Steam.
Jan 11 03:17:42 steamdeck kernel: BTRFS info (device mmcblk0p1): using crc32c (crc32c-intel) checksum algorithm
Jan 11 03:17:42 steamdeck kernel: BTRFS info (device mmcblk0p1): using free space tree
Jan 11 03:17:42 steamdeck kernel: BTRFS info (device mmcblk0p1): bdev /dev/mmcblk0p1 errs: wr 0, rd 0, flush 0, corrupt 21, gen 0
Jan 11 03:17:42 steamdeck kernel: BTRFS info (device mmcblk0p1): enabling ssd optimizations
Jan 11 03:17:42 steamdeck udisksd[1691]: Mounted /dev/mmcblk0p1 at /run/media/deck/1aa748c3-177d-4b03-8fee-496e65bb203d on behalf of uid 1000
Jan 11 03:23:44 steamdeck dbus-daemon[560]: [system] Activating via systemd: service name='org.freedesktop.home1' unit='dbus-org.freedesktop.home1.service' requested by ':1.165' (uid=0 pid=4239 comm="sudo lsblk -d /dev/mmcblk0 /dev/mmcblk0p1")
Jan 11 03:23:57 steamdeck sudo[4239]:     deck : TTY=pts/1 ; PWD=/home/deck ; USER=root ; COMMAND=/usr/bin/lsblk -d /dev/mmcblk0 /dev/mmcblk0p1
Jan 11 03:24:09 steamdeck dbus-daemon[560]: [system] Activating via systemd: service name='org.freedesktop.home1' unit='dbus-org.freedesktop.home1.service' requested by ':1.166' (uid=0 pid=4309 comm="sudo blkid /dev/mmcblk0 /dev/mmcblk0p1")


Hi I removed the fstab line but the issue persist my sd is btrfs

**Comment by bertogg** [comment] 2024-01-11 12:18
> Hi I removed the fstab line but the issue persist my sd is btrfs

The Steam Deck only automounts external drives with ext4 filesystems.

**Comment by Retragrade** [comment] 2024-01-15 00:02
> @Retragrade
> 
> You are using an additional, third-party auto-mount script (https://github.com/scawp/Steam-Deck.Mount-External-Drive or a variation of that one) so there might be interactions. Try disabling it / removing it and see if you still have problems.
> 
> ```
> Dec 29 18:52:58 steamdeckGJ automount.sh[593]: Error mounting /dev/mmcblk01p: SteamOS does ext4 for us!
> Dec 29 18:52:58 steamdeckGJ systemd[1]: [external-drive-mount@mmcblk01p.service](mailto:external-drive-mount@mmcblk01p.service): Main process exited, code=exited, status=2/INVALIDARGUMENT.
> ```

Uninstalling the third-party auto-mount script did the trick. Thank you very much!

**Comment by XargonWan** [comment] 2024-01-23 20:30
> > What if my micro sd suddenly doesnt mount either, but I also dont have an mmcblk0p1 entry on my fstab file?
> 
> For people that are having problems mounting their SD cards, please run the following commands and paste their output:
> 
> ```
> # sudo lsblk -d /dev/mmcblk*
> # sudo blkid /dev/mmcblk*
> # sudo e2fsck -n -f /dev/mmcblk0p1
> # grep mmcblk /etc/fstab
> # sudo journalctl -b | grep -E 'mmcblk|steamos-automount'
> ```

I have the same issue, however my sd card got a custom name, but I never had issue prior SteamOS 3.5 and unfortunately I cannot reformat it as I don't have a similar sized device as a backup target.

Here are my outputs, what are my options besides going into desktop mode to manually mount it at every boot?

I tried to add the entry in the fstab but I forgot the nofail flag and I had to boot into my live Ubuntu to comment it, so I prefer to use official methods instead of that to prevent issues (I understand why you prefer to not mount it at boot time).

**Comment by kisak-valve** [comment] 2024-01-23 20:38
Hello @XargonWan, `/dev/mmcblk0: LABEL="DeckSD" UUID="f8f9cb01-edfb-4dc2-9cbe-0bde09e8f2ee" BLOCK_SIZE="4096" TYPE="ext4"` looks abnormal. Since it doesn't include p1 (partition 1), to me that looks like the base block device was formatted without partitioning the storage medium, which is uncommon.

**Comment by XargonWan** [comment] 2024-01-24 08:01
> Hello @XargonWan, `/dev/mmcblk0: LABEL="DeckSD" UUID="f8f9cb01-edfb-4dc2-9cbe-0bde09e8f2ee" BLOCK_SIZE="4096" TYPE="ext4"` looks abnormal. Since it doesn't include p1 (partition 1), to me that looks like the base block device was formatted without partitioning the storage medium, which is uncommon.

Well to be fair I used Steam Deck's tool to format it (a friend sent me the bash script), but the format didn't happen directly on a Steam Deck but on a Manjaro VM as I didn't have a Steam Deck back then, the tool was taken from a Q1's Deck.

However, I have another question for a possible workaround: I wish to create non-steam game entry that will do the same action of clicking on "mount and open" on Desktop mode, how can I recreate that via command line?

**Comment by bertogg** [comment] 2024-01-24 17:06
> /dev/mmcblk0: LABEL="DeckSD" UUID="f8f9cb01-edfb-4dc2-9cbe-0bde09e8f2ee" BLOCK_SIZE="4096" TYPE="ext4" looks abnormal. Since it doesn't include p1 (partition 1), to me that looks like the base block device was formatted without partitioning the storage medium, which is uncommon.

Not only uncommon, but currently unsupported in SteamOS.

You can format the SD card on a different computer as long as you create a partition and use the ext4 filesystem (in that case I recommend that you pass additional options like `-O casefold` and `-m 0`), but it's better if you do it on the deck.

> I wish to create non-steam game entry that will do the same action of clicking on "mount and open" on Desktop mode, how can I recreate that via command line?

It should probably work if you use `udisksctl` but you're on your own if you do that :-)

**Comment by p1cueto** [comment] 2024-02-27 13:19
Everything works fine to me until this point, my terminal says

`e2fsck` 1.47.0 `(5-Feb-2023)
`Pass` 1: Checking inodes, blocks and sizes
`Inode` 786448 block 11 conflicts with critical metadata, skipping block checks.
`Inode` 786448 block 720896 conflicts with critical metadata, skipping block checks.

And does never stop trying to do something

**Comment by bertogg** [comment] 2024-03-04 13:54
That sounds like a corrupted filesystem, if it contained Steam games I would suggest you to format the sdcard and download the games again.

**Comment by kisak-valve** [comment] 2024-04-12 20:04
Closing per the note at https://github.com/ValveSoftware/SteamOS/issues/1208#issuecomment-1840689491, which has been promoted to the stable release.

If anyone is seeing a similar issue, that should be evaluated separately from this issue report with the information requested at https://github.com/ValveSoftware/SteamOS/issues/1208#issuecomment-1840689491.

**Closed by kisak-valve** 2024-04-12 20:04 UTC
Labels: Need Retest
