### ISSUE TITLE
Steam Deck on-screen keyboard not working for certain games

### ISSUE THREAD

**Issue by moominfan** [ValveSoftware/SteamOS#855] opened 2022-09-21 10:12 UTC
#### Your system information

* Steam client version: 1660688177
* SteamOS version: 3.3.1 build 20220817.1
* Opted into Steam client beta?: No
* Opted into SteamOS beta?: No
* Have you checked for updates in Settings > System?: Yes

#### Please describe your issue in as much detail as possible:
When playing [Star Wars Battlefront 2 (Classic, 2005)](https://store.steampowered.com/app/6060/Star_Wars_Battlefront_2_Classic_2005/) on the Steam Deck, manually bringing up the on-screen keyboard and typing on it does not enter any text in game. I expected to be able to type in in-game text input fields but the input is not recognized.

This issue seems to affect other users as well and does not seem to be limited to this game as seen in [this reddit post](https://www.reddit.com/r/SteamDeck/comments/w5i3s4/issue_battlefront_2_2005_onscreen_keyboard_entry/.).

Keyboard inputs through Steam input work flawlessly.

#### Steps for reproducing this issue:

1. Open Star Wars Battlefront 2 (Classic, 2005) on the Steam Deck
2. Manually bring up the on-screen keyboard with steam + x keys
3. Try to input text in any text field

**Comment by james2432** [comment] 2022-11-09 14:05
Same for Lord of the rings online, it will freeze the keyboard:

Left joystick produces sounds but stays on the same letter(g in my case)

track pads are able to show the two pointers but clicking on letters does nothing

Left trigger for caps does not shift the case for letters.

Pressing A button does not type the letter

**Comment by james2432** [comment] 2022-11-10 07:05
Did some more testing, the only way I can type is using the touch screen. The joysticks, trackpads, buttons do nothing other than make some noise.

this is on the Lord of the rings login screen

**Comment by james2432** [comment] 2022-11-11 05:32
seems to work with new update

**Comment by MalkiNokternum** [comment] 2022-11-11 15:56
When I'm at the home screen the keyboard works fine, but it instantly stops working whenever I go into ANY game, I've tested multiple games, none of them allow on screen keyboard usage anymore when they used to. I tested in Stardew Valley, Terraria, Halo Infinite, and even Elden Ring but none of them allow the on screen keyboard anymore when they all used to, did a Steam Deck Update screw up the on screen keyboard?

**Comment by james2432** [comment] 2022-11-11 16:09
> When I'm at the home screen the keyboard works fine, but it instantly stops working whenever I go into ANY game, I've tested multiple games, none of them allow on screen keyboard usage anymore when they used to. I tested in Stardew Valley, Terraria, Halo Infinite, and even Elden Ring but none of them allow the on screen keyboard anymore when they all used to, did a Steam Deck Update screw up the on screen keyboard?

updating to os build 20221003.100 on preview works for me. Previous preview build was broken

**Comment by MalkiNokternum** [comment] 2022-11-11 16:18
> > When I'm at the home screen the keyboard works fine, but it instantly stops working whenever I go into ANY game, I've tested multiple games, none of them allow on screen keyboard usage anymore when they used to. I tested in Stardew Valley, Terraria, Halo Infinite, and even Elden Ring but none of them allow the on screen keyboard anymore when they all used to, did a Steam Deck Update screw up the on screen keyboard?
> 
> updating to os build 20221003.100 on preview works for me. Previous preview build was broken

That fixed it thanks :D I was in the beta channel so I didn't have any update showing so I had to swap to the preview channel to update

**Comment by Jjarrard** [comment] 2022-11-14 01:32
Also when writing a caption for an ingame screenshot (post game close), the keyboard is there, but does not print letters into the comment box. Tried touchpads, touchscreen, analogue with trigger. Had a few issues recently where the key presses aren't picked up.

**Comment by kisak-valve** [comment] 2022-12-16 19:35
Closing per the last handful of comments.

Hello @Jjarrard, if you're able to reproduce your issue on an up to date system, please open a new issue report with more details on how the similar issue can be reproduced.

**Closed by kisak-valve** 2022-12-16 19:35 UTC
Labels: Need Retest

**Comment by 14142000** [comment] 2025-11-24 12:45
This is a steam issue as a whole, as windows also has this issue on GTA V and the Cod games
