### ISSUE TITLE
[Feature request] Add "Steam for Windows" Repository

### ISSUE THREAD

**Issue by Poahe** [ValveSoftware/SteamOS#611] opened 2017-09-07 14:25 UTC
#### Steps for reproducing this issue:

There is no "Steam for Windows" Repository in Valve Github. It have huge community and it "musthave"

**Comment by kisak-valve** [comment] 2017-09-07 15:04
Closing as a duplicate of https://github.com/ValveSoftware/steam-for-linux/issues/5160.

**Closed by kisak-valve** 2017-09-07 15:04 UTC
