### ISSUE TITLE
Create a truly portable (plug-n-play) SteamOS installation on an external SSD/HDD

### ISSUE THREAD

**Issue by charlesRedwoodPlains** [ValveSoftware/SteamOS#782] opened 2022-05-08 00:57 UTC
SteamOS needs an easy option to install to a portable HDD/SSD.

On Windows this can easily be done with Rufus and ticking the "Windows-to-go" feature. However steam games run better on Linux/Proton (awesome work Valve !!) and it would be preferable to have a portable SteamOS rather than a portable Windows.

Here are two links where you can create a portable Ubuntu (the steps are tedious and difficult and hardly any users will go to such trouble):
- https://medium.com/@abrarahmedsyed/how-to-create-a-truly-portable-plug-n-play-ubuntu-installation-on-an-external-ssd-hdd-7aaadc7d796a
- https://www.58bits.com/blog/2020/02/28/how-create-truly-portable-ubuntu-installation-external-usb-hdd-or-ssd

**Comment by kisak-valve** [comment] 2022-05-08 01:05
Hello @charlesRedwoodPlains, please do not intentionally open duplicate issue reports. Closing as a duplicate of #773.

**Closed by kisak-valve** 2022-05-08 01:05 UTC

**Comment by charlesRedwoodPlains** [comment] 2022-05-08 01:43
Low EQ approach:
1. User notes lack of a feature.
2. Kisak says "the feature is there, stop worrying".
3. User responds with several citations showing the lack of a feature.
4. Kisak _intentionally_ closes user's feature request with snarky tone.

A more emotionally intelligent approach:
1. Recognize the technical validity of the feature request.
2. State that the feature request doesn't align with the team's roadmap hence marking it as a no-fix.
3. User disappointed but respects the fact that they got a hearing and acknowledgement of the feature's rationale from a member of the team.
4. User understands that steam team can not add every feature and leaves the interaction satisfied.

**Comment by kisak-valve** [comment] 2022-05-08 01:53
The missing detail here is that any and all effort regarding SteamOS is going towards SteamOS 3, and at this point, it has only been released as a recovery image for the Steam Deck. Once a general purpose installer has been released for this newer effort has happened, then any potential quirks with it can be evaluated. It's highly unlikely for any changes to reach production with the older SteamOS 2 installer.

**Comment by charlesRedwoodPlains** [comment] 2022-05-08 01:59
Thanks dude keep up the great work. We all love you and we love Valve for the contribution you make.

I say this truthfully and not sarcastically.
