### ISSUE TITLE
Will be SteamOS  using systemd?

### ISSUE THREAD

**Issue by DarkminecrafterHD** [ValveSoftware/SteamOS#403] opened 2015-10-27 03:56 UTC
As SteamOs Alchemist is based on Debian Wheezy, that's systemd free i'm supose alchemist will be also free of it, corect me if i'm wrong

But what about Brewmaster?

**Comment by not83** [comment] 2015-10-27 04:28
Not a bug report. Try moving this to the SteamOS community discussion

**Comment by sharkwouter** [comment] 2015-10-27 12:34
You can install systemd in wheezy, but it is not the default.

**Comment by johnv-valve** [comment] 2015-10-27 13:35
brewmaster uses systemd

**Closed by johnv-valve** 2015-10-27 13:35 UTC

**Comment by DarkminecrafterHD** [comment] 2015-10-27 14:02
Thanks you all
I know that this is a bug report and that shouldn't be here.
but i wanted to known from the developers and not form anyone else.
my apologies for disturbing you
