### ISSUE TITLE
The terminal doesn't work

### ISSUE THREAD

**Issue by Vladislavuz** [ValveSoftware/SteamOS#724] opened 2020-12-04 16:35 UTC
The terminal does not work after expert installation with a change of the default language.

**Comment by stephenlake** [comment] 2021-01-27 10:49
Duplicate of https://github.com/ValveSoftware/SteamOS/issues/321

**Comment by kisak-valve** [comment] 2021-01-27 10:54
Thanks @stephenlake, closing as a duplicate.

**Closed by kisak-valve** 2021-01-27 10:54 UTC
