### ISSUE TITLE
Nit: steamos-add-to-steam has wrong mimetype list in SSH

### ISSUE THREAD

**Issue by cybik** [ValveSoftware/SteamOS#1019] opened 2023-04-26 13:25 UTC
#### Your system information

* Steam Deck

##### Expected
Running `/usr/bin/steamos-add-to-steam` against an exe from an SSH session _works_.
##### Observed
Running `/usr/bin/steamos-add-to-steam` against an exe from an SSH session _fails_.

##### Cause
The following block is bad:

```sh
mime=$(xdg-mime query filetype "$file")
case "$mime" in
    "application/x-desktop"|"application/x-ms-dos-executable")
        add_to_steam "$file"
        ;;
```

Specifically, on latest SteamOS, running `xdg-mime query filetype launcher.exe` returns `application/x-dosexec`, which doesn't match the argument list, and thus fails.

Note that this happens from an SSH context. Running from a terminal in desktop, the expected mimetype gets returned.

**Comment by bertogg** [comment] 2023-04-26 13:44
This is not because of the SteamOS version but because of the underlying tool that `xdg-mime` uses. That depends on whether you're running it from a graphical session or not.

If you log in via ssh:

```
$ xdg-mime query filetype /path/to/file.exe
application/x-dosexec
```

If you open a terminal on the Steam Deck and run the same command:
```
$ xdg-mime query filetype /path/to/file.exe
application/x-ms-dos-executable
```

Here are the underlying tools used in both cases:

```
$ file --brief --mime-type /path/to/file.exe
application/x-dosexec

$ kmimetypefinder5 /path/to/file.exe
application/x-ms-dos-executable
```

But I think that this discrepancy should be handled so your report is valid.

**Comment by cybik** [comment] 2023-04-26 13:45
I literally realized that and edited my report as you typed your reply. Heh.

**Comment by bertogg** [comment] 2023-04-26 13:58
You can work around it if you run this first from the terminal: `$ systemd-run --user --shell`

**Comment by bertogg** [comment] 2023-09-29 16:29
Hi, I had a quick look at this but I'm not sure that there's a good, reliable way to run this script from an ssh session, this is not just about the mime types but also about actually adding the game.

So I'd say to use the `systemd-run` method that I described earlier, maybe the script can be updated to show a more explicit error message.

**Comment by cybik** [comment] 2023-09-29 17:31
I have to agree. There's no easy way to do this, and furthermore, there's no way to

* add a runner into `compatibilitytools.d` *_and_*
* add a game simply without the `systemd-run` shenanigans *_and_*
* set the new game's runner to the new `compatibilitytools.d` entry

I realize supporting non-steam game entries is entirely out of the normal scope of VALVe/Steam operations and there's no business incentive to, say, make an integration for <non-steam game> since there would be no IAP percentage perceived by VALVe through its payment solution, but still. Easier non-steam entry management would be a nice user-first feature.

**Comment by bertogg** [comment] 2023-10-06 12:39
> add a game simply without the systemd-run shenanigans

I had a second look and I think the current script can be improved to avoid doing that. I cannot promise it'll make it on time for SteamOS 3.5 but I'll keep you up-to-date.

**Comment by bertogg** [comment] 2023-11-28 15:22
It didn't make it to 3.5 in the end but it'll be in 3.6.

**Comment by bertogg** [comment] 2024-05-15 08:53
This should be fixed in SteamOS 3.6, currently in preview. If anyone tries this and finds problem please report them here, thanks!

**Comment by cybik** [comment] 2024-05-15 15:28
It does not work :(

* `kmimetypefinder5` detects the mimetype of, say, `GenshinImpact_install_20240312154531.exe` (yes i'm addicted to this game) as `application/x-msdownload` if run through an SSH shell; that mimetype is not covered by the switch statement's cases
* `xdg-mime` detects it as `application/vnd.microsoft.portable-executable`, which is already technically better than last time

**Comment by bertogg** [comment] 2024-05-15 16:14
Oh, I see, can you confirm that adding `application/x-msdownload` and `application/vnd.microsoft.portable-executable` to the first branch of the `case` command solves the problem?

**Comment by cybik** [comment] 2024-05-15 19:28
I copied the script to ~/bin and ran it against the exe (my stuff is modded a bit).

Sure enough, it did add it!

Should I open a new ticket to request a way to use the CLI to provide metadata like art, and/or possibly a way to get the new steam library element's ID? It would be extremely practical if I got it back out, for scripting purposes.

Again, I know it's WAY out of spec and that VALVe has no incentive providing this kind of interface. Nevertheless, having the device as *the* Handheld whether a game is Steam or not, *in my opinion*, would only help cement it as a power player in the space in the long run.

**Comment by cybik** [comment] 2024-05-15 20:21
So running the same type of command from command line *sometimes* results in an empty element being added even though the exe exists (on desktop).

```
touch /tmp/addnonsteamgamefile && steam "steam://AddNonSteamGame/$(python3 -c "import urllib.parse;print(urllib.parse.quote(\"/A/VALID/path.exe\", safe=''))")"
``` 

it's really quirky *sometimes*. Maybe `steam://addnonsteamgame` also needs a fresh pair of eyes?

**Comment by bertogg** [comment] 2024-05-15 21:44
> So running the same type of command from command line sometimes results in an empty element being added even though the exe exists (on desktop).

I don't have a Deck at hand right now, if you would be so kind to list the exact steps to reproduce the problem (i.e. with the actual parameters that you're using) it would be helpful. Thanks!

> Should I open a new ticket to request a way to use the CLI to provide metadata like art, and/or possibly a way to get the new steam library element's ID?

You mean something like `steamos-add-to-steam --cover-art /path/to/image.jpg /path/to/binary.exe` ? If that's supported by the steam:// API then it would be easily doable, if not you would probably need to ask first in https://github.com/ValveSoftware/steam-for-linux

**Comment by cybik** [comment] 2024-05-15 21:52
> I don't have a Deck at hand right now, if you would be so kind to list the exact steps to reproduce the problem (i.e. with the actual parameters that you're using) it would be helpful. Thanks!

_Specifically_, I was not running it on Deck, but on standard PC, and was running it against a Zenless Zone Zero unpack. *While in the ZZZ directory containing ZZZ.exe*, the command I was running multiple times was:

```touch /tmp/addnonsteamgamefile && steam "steam://AddNonSteamGame/$(python3 -c "import urllib.parse;print(urllib.parse.quote(\"$(pwd)/ZZZ.exe\", safe=''))")"```

Sometimes it adds it. Sometimes it added an empty entry. Sometimes it added an unnamed entry *but* set the executable properly. Just now I ran it with no steam running, and it added it properly. I *then* ran it another time in a new console, against the now-running Steam instance, and it added an empty entry.

**Comment by cybik** [comment] 2024-05-15 22:00
> You mean something like `steamos-add-to-steam --cover-art /path/to/image.jpg /path/to/binary.exe`?

Something like that, yeah. Could also be additional parameters encoded into `steam://addnonsteamgame`, since the `steamos-add-to-steam` command line is actually only a helper on top of the URL handler.

I do see commands such as `gameproperties`, `specifycompattool`, 'setcustomartwork' and references to the 5 types of image assets in `steamui.so`, leading me to believe that editing game entry properties (non-steam or otherwise) using steam URL handling is possible but extremely unwieldy and undocumented (at best). I'm thinking that's how sgdboop does its magicks.

All of that does not help with getting the newly-added non-steam game's ID, mind you.

**Comment by kisak-valve** [comment] 2024-06-28 18:19
Closing because this issue appears to be resolved. Yes, the follow up request should be tracked separately.

**Closed by kisak-valve** 2024-06-28 18:19 UTC
