### ISSUE TITLE
`Native Color Temperature` option is applied to external displays. This has been an issue since for almost a YEAR now!

### ISSUE THREAD

**Issue by ahydronous** [ValveSoftware/SteamOS#1599] opened 2024-08-15 11:19 UTC
#### Your system information

* Steam client version: 17222380543
* SteamOS version: 3.6.9
* Opted into Steam client beta?: [Yes] 
* Opted into SteamOS beta?: [Yes] 
* Have you checked for updates in Settings > System?: [Yes]

#### Please describe your issue in as much detail as possible:
Going to `Settings` > `Display` > `Use Native Color Temperature` and toggling it off will apply the internal display color temperature shift to external displays.
This should not happen as external displays have their own color temperature configuration, and do not have the deficiency of the Deck LCD display. 

#### Steps for reproducing this issue:

1. Connect external display
2. Go to `Settings` > `Display` > `Use Native Color Temperature` and toggle it off 
3. External display shifts to incorrect color temperature

This issue has been happening since at least 17 november 2023: https://steamcommunity.com/app/1675200/discussions/0/7529517132619009854/

It has also been reported before, twice:
https://github.com/ValveSoftware/SteamOS/issues/1570
https://github.com/ValveSoftware/SteamOS/issues/1297

Please take action on this. Early Deck adopters should not be punished for supporting you.

**Comment by kisak-valve** [comment] 2024-08-15 13:18
Hello @ahydronous, please do not intentionally open duplicate issue reports.

Closing as a duplicate of #1570.

**Closed by kisak-valve** 2024-08-15 13:18 UTC

**Comment by ahydronous** [comment] 2024-08-15 15:57
Ah my bad. I thought maybe the issue was forgotten about.
A friend tried to write a preliminary solution himself (a script that responds to anything being plugged in/out of `DisplayPort-0`, since the internal display is always connected to `eDP`, but he couldn't figure out how to enable/disable `native color space`.
