### ISSUE TITLE
SteamLibrary keeps being recreated on microSD card despite being removed in SteamOS and in Desktop Mode (on the Steam Deck non-OLED)

### ISSUE THREAD

**Issue by eevyern** [ValveSoftware/SteamOS#1288] opened 2023-12-06 05:53 UTC
#### Your system information

* Steam client version: 1700676668
* SteamOS version: 3.5.7
* Opted into Steam client beta?: No
* Opted into SteamOS beta?: No
* Have you checked for updates in Settings > System?: Yes

#### Please describe your issue in as much detail as possible:
I recently used rEFInd to fix a booting issue I had after the SteamOS 3.5 update (that updated the BIOS). However, after using the rEFInd repo to fix the issue about a week ago, I realised SteamOS kept registering a Steam Library folder on my microSD card (and setting it as default).

I've tried removing the library through the SteamOS interface, and through manually deleting the libraryfolder.vdf file in the microSD card. However, upon rebooting into SteamOS, the library reappears as if it was never deleted.

I did some digging and realised some people were having the reverse problem on the Steam github - while I can't seem to remove my library folder, they can't add a new one. I've looked at my `content_log.txt` and noticed this:

```
[2023-11-28 02:43:12] NotifyAddDrive: re-adding drive folder: /run/media/deck/SHARE/steamapps
[2023-11-28 02:43:12] Mounted library folder "/run/media/deck/SHARE" : content id 7909078659946158336
[2023-11-28 02:43:12] Loaded 8 apps from install folder "/home/deck/.local/share/Steam/steamapps\appmanifest_*.acf".
[2023-11-28 02:43:12] Loaded 153 apps from install folder "/var/mnt/SteamLibrary/SteamLibrary/steamapps\appmanifest_*.acf".
[2023-11-28 02:43:12] Loaded 0 apps from install folder "/run/media/deck/SHARE/steamapps\appmanifest_*.acf".
[2023-11-28 02:43:12] Triggered async write of Steam library folders configuration (3 libraries).
```

Disclaimer: I'm a bit of a Linux noob, so I may need help with some commands, if they're needed for debugging.

#### Steps for reproducing this issue:

1. Remove 'External SD Card' as a library folder through Gaming Mode.
2. Switch to Desktop Mode, and then delete the `steamapps` folder and `libraryfolder.vdf` from the SD card drive.
3. Reboot.

Result: Once rebooted into Gaming Mode, the 'External SD Card' reappears as a Library folder, and is automatically set as default.

**Comment by katherinehackworth** [comment] 2024-05-28 04:14
still occuring

**Comment by bertogg** [comment] 2024-05-31 14:24
Hello, I'm not sure that I understand the issue. It is normal that when you insert an SD card Steam creates a library there, or are you talking about the fact that it becomes the _default_ library?

**Comment by eevyern** [comment] 2024-05-31 14:37
> Hello, I'm not sure that I understand the issue. It is normal that when you insert an SD card Steam creates a library there, or are you talking about the fact that it becomes the _default_ library?

Throughout the entire scenario, I never took out or reinserted the SD card. After I remove the SD card as a library, and restart SteamOS, the library is automatically re-added in the 'Libraries' section, and is made the default library. So there are 2 issues, for me at least:

1. Like you understand, the face that it becomes the default library
2. That despite not being moved, Steam still reintroduces the deleted library folder from the SD card back to the list of Steam Libraries.

If I can provide any other details to make this clearer, please let me know.

**Comment by bertogg** [comment] 2024-05-31 15:13
I see, thanks.

Yes, I think that this is a duplicate of https://github.com/ValveSoftware/steam-for-linux/issues/10225

**Comment by kisak-valve** [comment] 2024-05-31 15:22
I wouldn't consider SteamOS automatically recreating folders so that it's in a ready to use state a bug.

Closing in favor of steam-for-linux#10225.

**Closed by kisak-valve** 2024-05-31 15:22 UTC
