### ISSUE TITLE
The problem with the cursor in games launch via proton

### ISSUE THREAD

**Issue by vladislavyuzbekov** [ValveSoftware/SteamOS#695] opened 2019-10-04 07:56 UTC
#### Your system information

* Steam client version: 2.0:1:2:195
* 

SteamOS version: 1569522541

Opted into Steam client beta?: [Yes]

Opted into SteamOS beta?: [Yes]

Have you checked for updates in Settings > System?: [Yes]

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen.

The problem with the cursor in games launch via proton. This problem is seen only in SteamOS. On other operating systems the cursor works fine. After pressing any key the cursor becomes inactive or disappears. 

#### Steps for reproducing this issue:

1. 
2. 
3.

**Comment by kisak-valve** [comment] 2019-10-04 12:39
Hello @vladislavyuzbekov, this is the third time you've opened an issue report for the same issue, which was previously reported at https://github.com/ValveSoftware/Proton/issues/2849, #688.

Intentionally opening duplicate issue reports is against the [Code of Conduct](https://github.com/ValveSoftware/SteamOS#conduct) for this issue tracker and if you continue to do so, I'll be forced to take action.

Closing as a duplicate of https://github.com/ValveSoftware/Proton/issues/2849 / #475.

**Closed by kisak-valve** 2019-10-04 12:39 UTC
