### ISSUE TITLE
Updating large games on MicroSD card result in progress bar freezing

### ISSUE THREAD

**Issue by GaiZhenbiao** [ValveSoftware/SteamOS#1633] opened 2024-09-12 08:18 UTC
#### Your system information

* Steam client version: 1721173382
* SteamOS version: 3.5.19
* Opted into Steam client beta?: No
* Opted into SteamOS beta?: No
* Have you checked for updates in Settings > System?: Yes

#### Please describe your issue in as much detail as possible:
I was downloading a update of Shin Megami Tensei V: Vengeance. Steam downloaded the content and "Patching" no problem. Then it says "installing" and the expected finishing time takes forever (> 1 Year). However, in the Storage section of the settings the remaning storage space do decreases when I switch the page back and force to refresh it. In the download page if you wait long enough you can see the progress bar value suddenly increases a lot (like 0% to 50%) and stuck again. 

#### Steps for reproducing this issue:

1. Download a large game (in my case, around 30GB)
2. Install a update of it that requires writing the entire game twice.
3. See if the progress bar stuck.

**Comment by unclejack** [comment] 2024-09-14 15:43
This is a duplicate of https://github.com/ValveSoftware/SteamOS/issues/974. It might be less of an issue on SteamOS 3.6.x depending on the quality of the microSD card.

**Comment by kisak-valve** [comment] 2024-09-14 16:47
Closing in favor of the older issue report.

**Closed by kisak-valve** 2024-09-14 16:47 UTC
