### ISSUE TITLE
Add package `xdg-desktop-portal-gtk` to SteamOS

### ISSUE THREAD

**Issue by jefetienne** [ValveSoftware/SteamOS#795] opened 2022-06-09 04:08 UTC
Some flatpaks require the installation of this package to open external links.

To reproduce this issue, the latest [Unity Hub](https://github.com/flathub/com.unity.UnityHub)   at version 3.x.x opens with a sign-in page, but clicking "Log In" does nothing as it is unable to externally open the default browser for sign-in. I had to disable the read-only lock on the root filesystem to install the `xdg-desktop-portal-gtk` package and restart my device to get it working.

**Comment by kisak-valve** [comment] 2022-06-09 12:13
Possible duplicate of #775.

**Comment by bertogg** [comment] 2022-06-09 12:58
Yes, can you try rebooting or running `systemctl restart --user xdg-desktop-portal`, and then immediately launching UnityHub?

**Comment by kisak-valve** [comment] 2022-06-09 13:22
Closing in favor of #775.

**Closed by kisak-valve** 2022-06-09 13:22 UTC
