### ISSUE TITLE
Internal deck controls not working after 3.6.19 update.

### ISSUE THREAD

**Issue by BlackStargenX** [ValveSoftware/SteamOS#1683] opened 2024-10-26 04:02 UTC
#### Your system information

* Steam client version:
* SteamOS version: 3.6.19
* Opted into Steam client beta?: [No] 
* Opted into SteamOS beta?: [No] 
* Have you checked for updates in Settings > System?: [Yes]

#### Please describe your issue in as much detail as possible:
ControllerID:MHDA3071358
LCD steam deck.
SteamID:76561198247820298

After the 3.6.19 my internal face control will not work. Including joysticks and trackpads.
Their not broken as downgrading the os or switching to the beta channel brings back their functionality.
I also tried looking at the Jupiter info
"path": "/dev/hidraw3",

"vendor_id": 10462, "product_id":4613,

"serial_number": "",

"release_number": 768,

"manufacturer_string": "Valve Software", "product_string": "Steam Controller",

"usage page": 65535,

"usage": 1,

"Interface_number": 2,

"build timestamp": 1709502893,

"secondary_build_timestamp": 0,

"is_bootloader": false

Don't know if this will help.

I had reimage the system again, this time I connected to the Internet before it finished it's stepup install and first booted up in OS 3.6.19. controls are working. I also rebooted the system and their still working.  

I'm gonna go through regular steps I usually do and install proton GE and decky loader to see if anything happens. Will report if controls brake again.

#### Steps for reproducing this issue:

1. Updated to 3.6.19 from an older version.
2. 
3.

**Comment by BlackStargenX** [comment] 2024-10-26 04:12
I think I've might have found the problem.it might be proton tkg fault. I always installed proton GE and tkg for the games that runs great with them. 
But after installed them my internal controls stopped working again. So I started to uninstall them one at time.
Did tkg first loaded back in game mode and internal controls started working again.

So for some reason proton tkg and steam OS 3.6.19 doesn't like each other. Weird bug.

**Comment by BlackStargenX** [comment] 2024-10-26 04:20
Welp I celebrated too soon. The steam and ••• buttons are still not working. I'll restart the desk and test. If it still doesn't work I'll uninstall  proton GE and try again. Will report if I get those two buttons working again.

**Comment by BlackStargenX** [comment] 2024-10-26 04:26
Restarted the deck proton GE still installed and all buttons and track pass are working.
So my guess of either proton tkg or manually adding a custom proton version somehow is causing this bug in the LCD steam decks

**Comment by matte-schwartz** [comment] 2024-10-26 05:28
@kisak-valve this is a duplicate of https://github.com/ValveSoftware/SteamOS/issues/1678 but adding proton-tkg is the missing piece here.

1. Start on the SteamOS Stable image + client
2. Switch to desktop
3. Install protonplus as a flatpak
4. Install the latest version of proton-tkg
5. Switch back into Game Mode

I can now repro this issue as well.

SteamOS System Report after steps 1 -> 5 (and some earlier debugging):
[systemreport-20241026052549.txt](https://github.com/user-attachments/files/17529121/systemreport-20241026052549.txt)

Steam logs, since this is looking to maybe be a client issue of some sort:
[logs.tar.gz](https://github.com/user-attachments/files/17529122/logs.tar.gz)

**Comment by rostbacke** [comment] 2024-10-26 08:28
I can also reproduce this. After uninstallation of Proton-tkg the controller is recognized again.

**Comment by nl255** [comment] 2024-10-26 12:01
I have found switching to the beta channel fixes it.  Also I was unable to shut down normally (it would hang on "shutting down steam") but again the beta channel fixed it.

**Comment by kisak-valve** [comment] 2024-10-26 13:46
Hello @BlackStargenX, as @matte-schwartz noted, this issue is already being tracked at #1678. Since this issue report adds some more detail, I've gone ahead and transferred it to https://github.com/ValveSoftware/SteamOS/issues/1678#issuecomment-2439588660. Feel free to continue discussing the issue on the older issue report.

Closing as a duplicate.

**Closed by kisak-valve** 2024-10-26 13:46 UTC
