### ISSUE TITLE
White screen after trying to output overlay

### ISSUE THREAD

**Issue by Vladislavuz** [ValveSoftware/SteamOS#717] opened 2020-05-26 09:23 UTC
#### Your system information

* Steam client version: 1590412640
* SteamOS version: 2.0:1:2.195
* Opted into Steam client beta?: Yes
* Opted into SteamOS beta?: No
* Have you checked for updates in Settings > System?: Yes

#### Please describe your issue in as much detail as possible:
White screen after trying to output overlay. The problem appeared after the last steam client beta update.
https://yadi.sk/i/k4yLPkRoUVUrUw
#### Steps for reproducing this issue:

1. Try to output the overlay.

**Comment by sharkwouter** [comment] 2020-06-11 22:26
I've had a report of this happening on VaporOS today, it also seems to be the case on the stable steam client. GamerOS users are reporting it as well: https://github.com/gamer-os/gamer-os/issues/112

**Comment by jorgemartincuervo** [comment] 2020-06-24 11:03
I have tried to enable/disable the beta and with both versions I have the same issue: overlay is white.

**Comment by sharkwouter** [comment] 2020-06-24 11:28
To clarify this happens with Nvidia GPUs. The driver version doesn't seem to have much to do with it. A previous version of Steam had no such issue. I got this after a steam update on my GamerOS machine. No other changes were made to the system but that Steam update.

**Comment by jorgemartincuervo** [comment] 2020-06-24 11:47
Is there any way to force a downgrade? years back with the steam link there was a network issue and there was a way to force a specific version

**Comment by deephack1982** [comment] 2020-06-28 16:18
Can confirm this on my steam machine also.

Steam OS 2.0 1:2.195
Client from jun 20th 2020

**Comment by frioux** [comment] 2020-06-28 21:52
This *seems* to include other issues.  For example when my controller loses connection (maybe due to interference, maybe just because it timed out and turned off) when I turn it back on steam doesn't reconnect it to the game.  And because the overlay is all white, the only recourse is a full reboot :(

**Comment by frioux** [comment] 2020-06-29 05:43
Also, sometimes when you get the popover messages (like achievements) instead of them being a white rectangle at the bottom right for a little while, that white rectangle will persist the entire time you are running your game.  If you quit the game and start it back up the rectangle will come back, though it isn't there in the SteamOS UI.

**Comment by Paranoja** [comment] 2020-06-30 20:19
Confirming same issue on Fedora 31 with steamcompmgr and nVidia driver:
* overlay is completely white
* notification window is white
* in-game browser in some games is white
* non-steam games also have white overlay

**Comment by electrickite** [comment] 2020-07-03 01:40
Also confirming on Arch Linux running steamcompmgr with latest Steam client and NVIDIA proprietary driver. Same behavior: white rectangles for steam overlay notifications and completely white screen when activating the in-game. 

Also observed the same behavior on the GamerOS fork of steamcompmgr.

**Comment by deathxxx123** [comment] 2020-07-31 03:03
Confirm same issue **overlay is completely white** with GamerOS 18 and 19 with Nvidia 1060 6GB.
It's does not happen on any normal Distro.

**Comment by rezende** [comment] 2020-08-02 12:40
Just made the move yesterday from Windows to SteamOS and can't use the overlay because it's all white. Using the latest SteamOS with a GTX 1060 and proprietary NVIDIA drivers

**Comment by Vladislavuz** [comment] 2020-08-06 04:43
Thanks! The overlay is working.

**Comment by flibitijibibo** [comment] 2020-08-06 04:45
Fixed by August 5th Steam beta:

https://steamcommunity.com/groups/SteamClientBeta/announcements/detail/2735326880599543430

**Comment by frioux** [comment] 2020-08-06 05:08
Confirmed!  Works for me!  Woo!!!

**Comment by kisak-valve** [comment] 2020-09-11 14:43
Closing as fixed per "Fixed a regression with transparent visual selection for SteamOS overlays and on-screen keyboard causing invalid rendering on NVIDIA configurations" in the [2020-08-29](https://store.steampowered.com/news/74990/) Steam client update.

**Closed by kisak-valve** 2020-09-11 14:43 UTC
Labels: Need Retest
