### ISSUE TITLE
Rainbow Six Extraction Black Screen after 3.5.17

### ISSUE THREAD

**Issue by Formonitryl** [ValveSoftware/SteamOS#1407] opened 2024-03-02 16:56 UTC
* Steam client version:1709168962
* SteamOS version: 3.5.17
* Opted into Steam client beta?: No 
* Opted into SteamOS beta?: No
* Have you checked for updates in Settings > System?: Yes

Rainbow Six Extraction is marked as “Playable” so I expected to launch the game in gaming mode like I’ve normally been doing so. Instead, the game launches with a black screen IF set to fullscreen. Game audio is still present and I am able to hear the game’s menu when moving the joystick around.

In desktop mode, the game launches as it should. No black screen and no other problems. Now, if I change the settings to windowed or borderless, I am able to launch the game in gaming mode without a black screen BUT the screen will freeze after pressing the A button to start the game. Game audio will still be present and I am still able to hear the game’s menu when moving the joystick.

#### Steps for reproducing this issue:

1. Launch Rainbow Six Extraction in Gaming Mode after SteamOS 3.5.17
2. Black Screen after the launcher

**Comment by Formonitryl** [comment] 2024-03-02 20:31
UPDATE: Reinstalling fixed the black screen in gaming mode, but the game still freezes at the main screen after prompted to press the A button. Not sure why this specifically happens in gaming mode. I wish I knew what could be causing this.

I did not have this issue before 3.5.17.

**Comment by alasky17** [comment] 2024-03-07 17:03
@Formonitryl In my testing, this is due to the change which made ENABLE_GAMESCOPE_WSI=1 the default on OLED decks.  Could you confirm if setting ENABLE_GAMESCOPE_WSI=0 %command% as a launch option fixes all the new issues you are seeing with Rainbow Six Extraction on SteamOS 3.5.17?  I went ahead and filed a bug for this on the gamescope issue tracker since I was already investigating another game with a similar failure (see link above).

**Comment by Formonitryl** [comment] 2024-03-07 18:20
> @Formonitryl In my testing, this is due to the change which made ENABLE_GAMESCOPE_WSI=1 the default on OLED decks. Could you confirm if setting ENABLE_GAMESCOPE_WSI=0 %command% as a launch option fixes all the new issues you are seeing with Rainbow Six Extraction on SteamOS 3.5.17? I went ahead and filed a bug for this on the gamescope issue tracker since I was already investigating another game with a similar failure (see link above).

Hi! I can confirm that the command you gave me worked! I was able to properly launch the game in gaming mode. Many thanks :)

**Comment by alasky17** [comment] 2024-03-07 19:39
@Formonitryl Thank you for confirming that! It looks like I don't have the power to close this issue, but I think it should be closed in favor of the gamescope one because that is where the root of the problem is.  If you find any other games where this command fixes a failure, it would be greatly appreciated if you could report them here:  https://github.com/ValveSoftware/gamescope/issues/1182

**Comment by kisak-valve** [comment] 2024-03-07 19:43
Closing in favor of https://github.com/ValveSoftware/gamescope/issues/1182.

**Closed by kisak-valve** 2024-03-07 19:43 UTC
