### ISSUE TITLE
Games with Easy Anti Cheat don't start because of new version glibc

### ISSUE THREAD

**Issue by positiveoctopus** [ValveSoftware/SteamOS#1708] opened 2024-11-05 12:46 UTC
#### Your system information

* Steam client version: 1726683985
* SteamOS version: 3.6.20
* Opted into Steam client beta?: [YNo] 
* Opted into SteamOS beta?: [No] 
* Have you checked for updates in Settings > System?: [Yes]

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen.

Games with EasyAntiCheat like Insurgency Sandstorm don't work anymore because they use an older version of glibc

#### Steps for reproducing this issue:

1. Start a game with EasyAntiCheat 
2. Wait for the client to reach 100%
3. It closes with Unexpected Error #1, that's because of glibc

**Comment by kisak-valve** [comment] 2024-11-05 15:17
Hello @positiveoctopus, please do not intentionally open duplicate issue reports. Closing as a duplicate of #1697 / https://github.com/ValveSoftware/Proton/issues/1651#issuecomment-2449711472

**Closed by kisak-valve** 2024-11-05 15:17 UTC
