### ISSUE TITLE
Steam Deck has stuttering issues in BETA and PREVIEW build.

### ISSUE THREAD

**Issue by swoozi** [ValveSoftware/SteamOS#814] opened 2022-07-17 22:42 UTC
#### Steam Deck 256G

* Steam client version 1657758194
* STEAM OS 3.3
* Opted into Steam client beta?: [Yes]
* Have you checked for system updates?: [Yes]

#### Steps for reproducing this issue:

1. Play a game and spin the in-game camera around
2. Set the GPU clock to a static clock and spin the in-game camera around to see the difference 
3. Solution? Go back to Stable Build until fixed.

This bug has now been passed into the Stable Build.
https://youtu.be/eGSU-_xUUD0

**Comment by swoozi** [comment] 2022-07-20 01:23
Steam client version 1658256710
This bug is still relevant in the latest beta update for the steam deck, July 19th

**Comment by McMarius11** [comment] 2022-07-26 15:48
i have the same issue, i tested for example Severed Steel, i'm also on the beta branch of steamos.
i just have to stand still and do nothing, it will jump from 60 to 58 and this happens every 3-5 seconds
https://steamcommunity.com/sharedfiles/filedetails/?id=2840718191

this is with gpu clock on 600
https://steamcommunity.com/sharedfiles/filedetails/?id=2840718433
it does not happen

**Comment by swoozi** [comment] 2022-07-26 19:17
> i have the same issue, i tested for example Severed Steel, i'm also on the beta branch of steamos. i just have to stand still and do nothing, it will jump from 60 to 58 and this happens every 3-5 seconds https://steamuserimages-a.akamaihd.net/ugc/1901100246150423081/CC68A47D52B2D37187EC99212EEEA3C6E245D713/?imw=5000&imh=5000&ima=fit&impolicy=Letterbox&imcolor=%23000000&letterbox=false
> 
> this is with gpu clock on 600
> 
> https://steamuserimages-a.akamaihd.net/ugc/1901100246150424808/D2689D189860BDA95500BF96225EB8F909D5ABF4/?imw=5000&imh=5000&ima=fit&impolicy=Letterbox&imcolor=%23000000&letterbox=false it does not happen

yup, its been an issue I talked about and so did others for weeks now, I hope this week it gets fixed. lol.

**Comment by McMarius11** [comment] 2022-07-28 20:04
With the latest beta update I can't reproduce the problem, how about you?

**Comment by swoozi** [comment] 2022-07-30 18:54
> With the latest beta update I can't reproduce the problem, how about you?

I think they might've fixed it tbh, I still think the GPU doesn't clock fast enough but it's definitely better. I have since then stayed in the preview build since I consider it good enough for now.

**Comment by 1basti1** [comment] 2022-08-01 18:01
I still have stutters on preview. I play a nonsteam game right now (Trackmania 2020) a static GPU clock resolves the issue...

**Comment by 1basti1** [comment] 2022-08-03 04:19
And now it's in the newly pushed stable. 

*Of course does not only happen with nonsteam games.

**Comment by hugopacheco** [comment] 2022-08-03 06:52
Just downloaded stable and I'm experiencing stuttering, I'll give a try to the static GPU clock workaround.

**Comment by swoozi** [comment] 2022-08-03 08:35
> Just downloaded stable and I'm experiencing stuttering, I'll give a try to the static GPU clock workaround.
report this to steam, lets get this fixed.

I made a video about it.
https://youtu.be/eGSU-_xUUD0

**Comment by TTimo** [comment] 2022-08-03 22:20
thank you - addressed in today's 3.3 hotfix

**Closed by TTimo** 2022-08-03 22:20 UTC

**Comment by Kuratius** [comment] 2022-08-03 22:26
Out of curiosity, what was the cause and fix of this issue? A wrong package version?

**Comment by TrainDoctor** [comment] 2022-08-03 22:30
> Out of curiosity, what was the cause and fix of this issue?

Seems to have been a regression/bug in gamescope of some kind.

**Comment by TTimo** [comment] 2022-08-03 22:51
https://github.com/Plagman/gamescope/commit/f6f5783e941f3dd93b8febd9ab33264bd62b9b5f for the curious
