### ISSUE TITLE
Problems with the cursor

### ISSUE THREAD

**Issue by vladislavyuzbekov** [ValveSoftware/SteamOS#688] opened 2019-08-30 03:58 UTC
#### Your system information

* Steam client version: 1566431379
* SteamOS version: 2.0:1:2.195
* Opted into Steam client beta?: [Yes] 
* Opted into SteamOS beta?: [Yes] 
* Have you checked for updates in Settings > System?: [Yes]

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen.

In all games that use proton, there are problems with the cursor when using the mouse. After the first click the cursor disappears or is not displayed. The problem is relevant only for SteamOS.

#### Steps for reproducing this issue:

1. 
2. 
3.

**Comment by kisak-valve** [comment] 2019-08-30 11:32
Hello @vladislavyuzbekov, please do not intentionally open duplicate issue reports. Closing as a duplicate of https://github.com/ValveSoftware/Proton/issues/2849 / #475.

**Closed by kisak-valve** 2019-08-30 11:32 UTC

**Comment by vladislavyuzbekov** [comment] 2019-08-30 13:27
Support Steam sends me here to report problems. This problem has not been resolved for a long time. My apologies! -- С уважением,Владислав Юзбеков+79604738017   30.08.2019, 14:32, "kisak-valve" <notifications@github.com>:Hello @vladislavyuzbekov, please do not intentionally open duplicate issue reports. Closing as a duplicate of ValveSoftware/Proton#2849 / #475.—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
