### ISSUE TITLE
Ability to switch clock speeds for docked and handheld

### ISSUE THREAD

**Issue by KingVulpes** [ValveSoftware/SteamOS#1762] opened 2024-12-29 19:45 UTC
It would be nice if we had the ability to switch clock speeds depending on if the Steam Deck was docked or in handheld. This would be great for if we wanted to conserve battery while portable but want max power when playing on a TV or Monitor.

**Comment by kisak-valve** [comment] 2024-12-29 19:55
Hello @KingVulpes, this request is functionally a duplicate of #1344.

Closing in favor of the older issue report.

**Closed by kisak-valve** 2024-12-29 19:55 UTC
