### ISSUE TITLE
3.6.20 Much more power consumption and less performance!

### ISSUE THREAD

**Issue by doctacybaninja** [ValveSoftware/SteamOS#1756] opened 2024-12-25 00:49 UTC
#### Your system information

* Steam client version: 
* SteamOS version: 3.6.20
* Opted into Steam client beta?: [No] 
* Opted into SteamOS beta?: [No] 
* Have you checked for updates in Settings > System?: [Yes]

#### Please describe your issue in as much detail as possible:
I have a steam deck LCD. I was on version 3.5.19 and I did a clean install of steam OS with the latest image on the steam website. So there is not a single unintended program that would influence the performance of my device. My steam deck is now at version 3.6.20.

I installed a low end game and noticed the power usage was significantly higher in comparisson to version 3.5.19. On 3.5.19 I could play the same game for 5 hours easily and now I get less than 4.5 hours of gameplay. The game also runs worse despite the higher power consumption. 

I also notice the fps graph is so jittery, a shark would be jealous of the amount of teeth the graph has. On 3.5.19 this was a straight line. On 3.6.20 the line is NEVER straight.

I expect this to be taken seriously, because a handheld needs as low power consumption as possible, and update 3.6.20 completely defeats the purpose of having a handheld. It was promised 3.6 would increase the performance by 10%, but as expected, this was a complete lie!

#### Steps for reproducing this issue:

1. Install any game
2. Play on low tdp.
3. compare the same game with another steam deck LCD which has 3.5.19 installed. 
4. let both versions' battery run from 100% to 50% and see how much difference there is between them.

**Comment by kisak-valve** [comment] 2024-12-25 01:14
Hello @doctacybaninja, please see https://github.com/ValveSoftware/SteamOS/issues/1689#issuecomment-2452579211. SteamOS 3.5 wasn't as accurate with TDP limits and is reporting numbers closer to what the hardware is actually doing.

Closing as a duplicate of #1689.

**Closed by kisak-valve** 2024-12-25 01:14 UTC
