### ISSUE TITLE
External monitor stays off/dark after switching to Gaming Mode

### ISSUE THREAD

**Issue by MadByteDE** [ValveSoftware/SteamOS#889] opened 2022-10-28 17:29 UTC
#### Your system information

System setup: [Github Gist](https://gist.github.com/MadByteDE/53652ecbc2de9b4a4e6234d1aa00436c)
* Steam client version: 3.3.2
* SteamOS version: 1666913041
* Opted into Steam client beta?: [Yes/No]  yes
* Opted into SteamOS beta?: [Yes/No]  yes
* Have you checked for updates in Settings > System?: [Yes/No] yes

#### Please describe your issue in as much detail as possible:

- Using the Steam Deck & official Steam Dock
- Using Display Port
- Default screen resolution is 2560x1440

After the latest Steam Beta update on boot, reboot or returning to gaming mode from desktop mode, my external monitor stays off / no signal.
- The internal display stays off as well
- Sounds are being played on the internal speakers (not on external monitor)

Re-connecting the USB-C cable will fix the issue.

**Comment by MadByteDE** [comment] 2022-10-30 22:09
It seems like sometimes I get an infinite "Checking installation" screen on the external monitor instead of no signal while I can hear the boot video sound on the SD speakers but the SD screen stays off - no visible menu. Key/mouse/stick input sounds can be heard but not seen until I re-plug the USB-C cable.

**Comment by MadByteDE** [comment] 2022-11-11 17:50
Still same issue on latest Beta. I reverted to stable for now since the issue is not present there.

**Comment by MadByteDE** [comment] 2022-11-19 08:27
Same issue with latest preview (1668841282).
- Disabling "OpenGL Composer" in developer settings seems to fix the issue, but introduces a black background when opening the Steam menu (as described in [this](https://github.com/ValveSoftware/SteamOS/issues/885#issuecomment-1295237640) issue comment)
- I still believe the issue is somewhat linked to #885

**Comment by MadByteDE** [comment] 2022-12-25 09:13
Still same issue with latest 3.4 stable release.

**Comment by hvarga** [comment] 2023-04-03 18:23
I can confirm from my side that I have the same issue. I am running SteamOS 3.4.6 on my Steam Deck. Can someone from Valve please take a look at this?

@MadByteDE, are you still experiencing this issue on newer SteamOS?

**Comment by lostgoat** [comment] 2023-04-04 23:29
Fix for this issue shipped in today's update:
https://store.steampowered.com/news/app/1675200/view/6385581887762033270

Thanks for the report.

**Closed by lostgoat** 2023-04-04 23:29 UTC

**Comment by hvarga** [comment] 2023-04-05 16:32
Thanks @lostgoat, I can confirm that, after switching to Beta channel, my external monitor is now working as expected when I manually set the native version and then reboot into gaming mode.

But we still have an issue with automatic detection of the native resolution, though. The automatic detection is still configuring my 2560x1080 to 1920x1080. I would probably have never encountered the issue that you have now fixed (manual set of resolution) in the first place if this automatic is working as expected.

This needs to be fixed as well since I also have a 4K TV on which I am plugging the Steam Deck. I guess a majority of other Steam Deck users are doing the similar. This means that I always need to manually change resolutions back and forth. It would be really great if a Steam Deck does this for me, automatically.

I suppose that you want me to create a new issue for this?

**Comment by hvarga** [comment] 2023-04-05 17:55
@lostgoat, it is kind-of hard to see the problem from the screenshots, but here it is.

![20230405192655_1](https://user-images.githubusercontent.com/2044225/230158551-5e04eee4-bf4d-477b-b8a3-3964dcc360bd.jpg)
![20230405192610_1](https://user-images.githubusercontent.com/2044225/230158554-115699da-63d1-4add-82e6-de908bb45fce.jpg)

The first one show the screen when I have "Automatically Set Resolution" enabled and the second one shows when I have this parameter disabled which grants me an ability to manually specify a resolution (which I have set to 2560x1080).

From those, you can see that "Automatically Set Resolution" is not actually the same resolution as the one that I have set manually (the second screenshot has more real estate). And that is what I was saying; the "Automatically Set Resolution" doesn't detect the correct native resolution. On my end, seems like it is setting to 1920x1080.

Just to clarify. We have two issues:

1. Booting into game mode with a manually set display resolution. This is actually what you have fixed and which I tested using Beta channel. Works perfectly.
2. "Automatically Set Resolution" doesn't detect the correct native resolution. This one is still an issue even in current Beta.

Those issues are only applicable in gaming mode. The desktop mode works perfectly.

I have never mentioned this, the reason why I was playing with this automatic/manual configuration of display resolution is because the Steam Deck is setting the highest available resolution in my games to 1920x1080 in case of "Automatically Set Resolution" set to enabled. But if I disable this and set my resolution manually to 2560x1080, then I am able to choose 2560x1080 in my games as well.

But maybe I am interpreting the "Automatically Set Resolution" in the wrong way in the first place? I assumed that "Automatically Set Resolution" SHOULD set external display to its native resolution. If that is true, then this is obviously not the case on my end since I am getting 1920x1080 and this is indeed a bug.

**Comment by jaded0** [comment] 2023-11-26 22:06
I'm still getting the blank screen, on the newest stable update on the steam deck.

**Comment by TheDarkeye4876** [comment] 2023-11-30 04:48
Same for me. If I'm using desktop mode, I will have to disconnect the external display before moving to Game Mode. Once it's back to game mode, I plug it back in. Kind of tedious really.
