### ISSUE TITLE
[Feature] Include networkmanager-openvpn in base image

### ISSUE THREAD

**Issue by brendenhoffman** [ValveSoftware/SteamOS#810] opened 2022-07-05 20:35 UTC
There is no reason a vpn should not be able to be configured on the steam deck, while there is little use for one outside of desktop mode, the lack of the packages which many vpns use makes it very hard to configure one if we choose to do so. The openvpn package is essential, however including networkmanager-openvpn would integrate seamlessly in KDE.
 Current SteamOS 3.3 beta

**Comment by maxi1134** [comment] 2022-11-23 22:54
I'd say Wireguard, this is *current year* not 2001.

Better, both. Since some people still have legacy intallations.

**Comment by brendenhoffman** [comment] 2022-11-24 00:00
OpenVPN is by no means obsolete... It's a requirement for a lot of VPNs. It's great that wiregaurd was implemented into the kernel in recent years, but not everything has migrated from OpenVPN to wiregaurd, nor will they until OpenVPN is actually obsolete

**Comment by MNarath1** [comment] 2023-03-22 23:04
> I'd say Wireguard, this is _current year_ not 2001.
> 
> Better, both. Since some people still have legacy intallations.

wireguard might be better at a purly technical standpoint but it suffers in other areas like clients not resolving domains on reconnects (pretty much destroys  autoreconnect for dynamic dns )

**Comment by bertogg** [comment] 2023-03-24 17:37
FYI this is being taken care of.

**Comment by Lazorne** [comment] 2023-06-02 05:41
> FYI this is being taken care of.

Just to confirm here you are adding both Wireguard and openvpn ? :)

**Comment by bertogg** [comment] 2023-06-02 10:55
Both networkmanager-openvpn and wireguard-tools

**Comment by louis993546** [comment] 2023-09-14 12:52
Which version of preview image has openvpn? I am testing on the preview channel and openvpn is still missing

**Comment by bertogg** [comment] 2023-09-14 12:58
I mean the _Main_ OS update channel, for example the `20230907.1000` build.

**Comment by louis993546** [comment] 2023-09-18 01:15
Just got the update and confirmed it works 👍 Thanks!

**Comment by bertogg** [comment] 2023-11-14 15:31
This is also in the SteamOS 3.5 betas, so I think we can close this issue.

**Comment by kisak-valve** [comment] 2023-12-23 01:57
Closing as implemented in SteamOS 3.5.

**Closed by kisak-valve** 2023-12-23 01:57 UTC
Labels: Need Retest
