### ISSUE TITLE
[Feature Request] Build Steam input into Steam OS Desktop mode natively at the Kernel level.

### ISSUE THREAD

**Issue by jazir555** [ValveSoftware/SteamOS#1589] opened 2024-08-08 04:32 UTC
The current implementation of Steam Input for Desktop Mode controls has a delay as the Steam Desktop application needs to launch first before custom button mappings are usable (like mouse control on the left trackpad or remapping the mouse click buttons). The default controls work first (like 10-15 or more seconds as Steam launches), then the controls stop working entirely for a few seconds as Steam starts up (3-5), and then I can _finally_ I'm able to use my custom mappings.

It would be great if you could build Steam Input into Steam OS's Kernel directly so that custom Desktop mappings are immediately usable and are independent of the Steam Desktop application. 

The other thing is this would allow steam input mappings to persist even when steam is closed. That would also allow summoning the virtual keyboard at all times since that would no longer be dependent on the Desktop application as well.

**Comment by kisak-valve** [comment] 2024-08-08 11:21
Hello @jazir555, please do not intentionally open duplicate issue reports.

Closing as a duplicate of #1524.

**Closed by kisak-valve** 2024-08-08 11:21 UTC

**Comment by jazir555** [comment] 2024-08-08 21:28
Sorry @kisak-valve! I totally forgot I previously opened a thread for this, I apologize!
