### ISSUE TITLE
Brewmaster installer does not complete

### ISSUE THREAD

**Issue by pyredaemon** [ValveSoftware/SteamOS#453] opened 2015-12-27 20:12 UTC
Description (Short): 
Current brewmaster creates an incomplete installation.

Description (Long):
First, I should mention that I have to employ the workaround posted by user "gizmonicus" in this community post, https://steamcommunity.com/groups/steamuniverse/discussions/1/648814395798555095/

After successfully employing that workaround, the installation runs for several minutes, and then returns back to the "Next installation step" screen. It doesn't matter what you select, every item except "Install grub" and "Finish installation" (I don't remember the exact wording on those choices) returns.

If you reboot at that point, the boot just keeps cycling with a black screen. 
You can get to a grub menu though, and boot into recovery mode (there are actually two grub screens, one is blue, the second is a more familiar style grub screen). If you don't use recovery mode from the second grub screen, the machine will eventually bounce on its own, even if you're in the middle of a session.

You can finish the install by re-indexing intall media with apt-cdrom, and then running aptitude, and finishing the install (xorg, gnome, and lightdm).

After that, you may reboot the system, and it will boot into gnome-desktop and do some additional configuring, and load some (presumably proprietary drivers).

There's another issue, but I'll open a new case, because I have a feeling it's unrelated to the above errors, and this one is already kind of two bugs in one.

If you cannot reproduce this error, I would be willing to do it again and provide logs (tell me which ones i'll need).

Board: GIGABYTE GA-H81M-DS2V
Graphics Card:  Radeon HD7770

Hope that helps.

**Comment by ProfessorKaos64** [comment] 2015-12-27 20:16
>If you cannot reproduce this error, I would be willing to do it again and provide logs (tell me which ones i'll need).

List your exact steps for obtaining the median, creating the USB/CD, BIOS or UEFI. What is your hardware?

When you created your issue, this was lined above it:  
Please review the [guidelines for contributing](https://github.com/ValveSoftware/SteamOS/blob/master/contributing.md) to this repository.

**Comment by binary132** [comment] 2015-12-28 14:42
I had the same issue.  I used the installer image located at http://repo.steampowered.com/download/SteamOSDVD.iso and applied it to a USB stick.  I then mounted it as /cdrom as a workaround because the installer was complaining about missing cdrom.

I also noticed it failed to configure the package manager, ethernet, etc.  lightdm fails to start correctly on boot, indicating X is not found in the PATH value.

**Comment by binary132** [comment] 2015-12-28 14:44
(My motherboard is an Asrock FM2A88M Pro3, fwiw.)

**Comment by ProfessorKaos64** [comment] 2015-12-28 15:04
@binary132 , that [motherboard](http://www.newegg.com/Product/Product.aspx?Item=N82E16813157571) appears to be UEFI, why are you downloading the legacy BIOS image? Be careful as well with any APU chips, which may need disabled. Also I would like to know what GPU you are using. If you are using the APU only, that will likely not work at all, especially AMD.

Please review:
https://github.com/ValveSoftware/SteamOS/wiki

**Comment by binary132** [comment] 2015-12-28 16:03
That's the legacy image?  I just succeeded at what seems to be the full installation (booted in UEFI mode) by copying that ISO to USB with `dd`.  I suspect the issue was the software I used in Windows to apply the ISO to create a bootable USB perhaps.

I'm using a gtx960 with an x4-860k (non GPU fm2+ CPU.)

**Comment by ProfessorKaos64** [comment] 2015-12-28 16:07
The ISO is the legacy image (I have that information on the wiki, and it is also in the SteamOS DIY landing page). If you have a dual BIOS (UEFI and legacy BIOS), the legacy ISO for BIOS systems can work. I have a dual BIOS on my Gigabyte board. To install with UEFI, I specifically had to turn on the "Windows 7 features" and disable CSM, then specifically choose the UEFI USB stick on my boot menu. Choosing the non-UEFI entry before that would allow me to install using the ISO image. The .zip archive is for UEFI systems.

You are correct in using dd, which is the best tool for the job here, but albeit not the most user friendly for new users.

**Comment by binary132** [comment] 2015-12-28 16:17
Ah.  I tried the ISO approach after unzipping the folder to the USB failed (I am pretty sure it was the missing cdrom issue.)

Yes, I had booted the USB in UEFI mode.  Weird.

**Comment by binary132** [comment] 2015-12-28 16:18
Perhaps tonight I'll see if I can reproduce it with some different mobo settings.  :)

**Comment by binary132** [comment] 2015-12-28 16:19
Btw, the legacy ISO installer does install grub-uefi.

**Comment by pyredaemon** [comment] 2015-12-29 03:40
Dammit.

I found yet another USB stick, tried it, and it worked, all of it. Like the entire freakin' thing. No remounting anything, no hacking apt, and no cycling boot screen.

Which should be good, but now I'm a bit embarrassed, and disappointed. Really thought I was on to something, here.

*sigh* Well, @ProfessorKaos64 I'll answer your questions anyway. In case they ever end up being diagnostically helpful.

I unzipped the install files from this page, http://store.steampowered.com/steamos/buildyourown

The first set of instructions. They go to the root of a fat32 usb device.

Yeah, had the UEFI settings right (was running alchemy for the past year before this).

The weird thing is that I installed Alchemy from the same device I was trying to install this one from.

Doesn't mean I didn't so something wrong, but I certainly don't remember doing anything different.

Well, I leave this case in your hands. Will close if you wish, and will keep the other drive around, too, in case you want me to duplicate again (since it surely will on that drive, I tried the install 3 times)

**Comment by ProfessorKaos64** [comment] 2015-12-29 03:42
You close this as you see fit. I don't work for Valve or am affiliated with them. I just merely try to be helpful where I can. I appreciate you explaining things in case another person encounters this post. 

Have a happy new year!

On December 28, 2015 10:40:13 PM EST, Sable Marked Ferret <notifications@github.com> wrote:
>Dammit.
>
>I found yet another USB stick, tried it, and it worked, all of it. Like
>the entire freakin' thing. No remounting anything, no hacking apt, and
>no cycling boot screen.
>
>Which should be good, but now I'm a bit embarrassed, and disappointed.
>Really thought I was on to something, here.
>
>*sigh* Well, @ProfessorKaos64 I'll answer your questions anyway. In
>case they ever end up being diagnostically helpful.
>
>I unzipped the install files from this page,
>http://store.steampowered.com/steamos/buildyourown
>
>The first set of instructions. They go to the root of a fat32 usb
>device.
>
>Yeah, had the UEFI settings right (was running alchemy for the past
>year before this).
>
>The weird thing is that I installed Alchemy from the same device I was
>trying to install this one from.
>
>Doesn't mean I didn't so something wrong, but I certainly don't
>remember doing anything different.
>
>Well, I leave this case in your hands. Will close if you wish, and will
>keep the other drive around, too, in case you want me to duplicate
>again (since it surely will on that drive, I tried the install 3 times)
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/ValveSoftware/SteamOS/issues/453#issuecomment-167710961

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Closed** 2015-12-29 03:49 UTC
