### ISSUE TITLE
Spanish USB keyboard does not work correctly in Gaming Mode

### ISSUE THREAD

**Issue by Labestiajake** [ValveSoftware/SteamOS#1583] opened 2024-07-27 14:24 UTC
#### Your system information

* Steam client version: 1722028579
* SteamOS version: 3.6.8 20240626.100
* Opted into Steam client beta?: [Yes/No] Yes
* Opted into SteamOS beta?: [Yes/No] Yes
* Have you checked for updates in Settings > System?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
In Gaming Mode, the Spanish USB keyboard does not write the Spanish characters correctly (ñ) or the symbols in their order. As if the keyboard layout is not changed. The virtual keyboard is in Spanish and works without problems. In desktop mode, both the virtual and USB keyboards work well without problems.

#### Steps for reproducing this issue:

1. I turn on the Steam Deck.
2. In the search bar, I type and it's wrong.
3. When a game asks for my email I can't write the @.

**Comment by bertogg** [comment] 2024-08-06 09:39
This is a duplicate of https://github.com/ValveSoftware/SteamOS/issues/798

**Closed** 2024-08-06 11:01 UTC
