### ISSUE TITLE
[SteamDeck] default vm.swappiness = 100, over prioritizing the use of swap over RAM

### ISSUE THREAD

**Issue by rstrube** [ValveSoftware/SteamOS#899] opened 2022-11-08 17:21 UTC
#### Your system information

* Steam client version: 1667866781
* SteamOS version: 3.3.2
* Opted into Steam client beta?: Yes
* Opted into SteamOS beta?: Yes
* Have you checked for updates in Settings > System?: Yes

#### Please describe your issue in as much detail as possible:
"Swappiness" set to 100, causing aggressive use of swap, even when RAM is free.  Default value is "60", many distros set this to a value closer to "10" or "20" to have the kernel attempt to use RAM more often and prioritize swap less.

#### Steps for reproducing this issue:
1. Switch to "Desktop Mode"
2. Open a terminal
3. Enter: `sysctl vm.swappiness`
4. Note that the `vm.swappiness` value is `100` which is significantly higher than the default value of `60`

**Comment by Mushoz** [comment] 2023-02-03 09:32
Not only does it improve performance as can be seen in these benchmarks: https://www.youtube.com/watch?v=od9_a1QQQns

It also REDUCES wear & tear on the SSD by using less write cycles for swapping out memory to the swap file. Changing this value to a more sane value is a no brainer IMO.

**Comment by manuelafm** [comment] 2024-01-19 20:05
This has been changed a while back and for the latest stable releases (3.5) `vm.swappiness` is back to 60.

**Comment by Kazlehoff** [comment] 2024-01-19 22:17
Question.. why 60? why not configure it to function like all computers since always? ram first, then storage, with a value of 1?

**Comment by guilhermepiccoli** [comment] 2024-01-26 11:12
> Question.. why 60? why not configure it to function like all computers since always? ram first, then storage, with a value of 1?

Hi, this is the default kernel setting - did you or anyone manage to test 60 vs a lower value, to see if that improves perf? Is there any suggestion of a test we could do to look into that?

**Comment by bertogg** [comment] 2024-01-26 13:24
Apart from what @guilhermepiccoli said, it sounds like there's a misconception here: the swap is not an extension of the RAM and `swappiness` is not a mechanism to use swap when there's RAM available.

Any change to the default value should be backed by data.

**Comment by Kazlehoff** [comment] 2024-01-28 00:56
Data would be pretty easy to gather from anyone who has been using CryoUtils. Setting swappiness to 1 is one of the changes it makes.

**Comment by lostgoat** [comment] 2024-01-28 05:44
We haven’t seen workloads where this has a significant effect. But if anyone can provide comparisons in the following format that show that this change would be beneficial, then we are open to re-evaluate:

| Game Name | Swappiness | Frametime Avg| Frsmetime Min | Frametime Max |
|----------|----------|----------|-| -|
| Game 1   |  1|    |  | |
| Game 1    | 60 |   | | |

Please ensure results are reproducible before sharing.

**Comment by Kazlehoff** [comment] 2024-01-28 13:29
I'll respond with my own as soon as im able (alas, work.)

**Comment by Ponjen** [comment] 2024-01-28 21:06
Only game I have that needs a modified swap space is Midnight Suns. Without it, the game would consistently hard crash when sleeping at the Abby, or even during combat. Usually about 30 minutes to an hour in. As long as the swap space is a minimum of 2GB, the crashes stop. Other's reports on ProtonDB for that game confirm the issue and solution as well.

I have tested with removing CryoUtlities just to confirm. Got crashes. Once applying it, crashes stopped. These would be hard crashes that forced you to shut off the Deck by holding the power button. Currently Palworld has the same issue, but Cryo made no difference there. It's just a memory leak in the game that's resolved by reloading your save every now and then.

**Comment by Sunspark-007** [comment] 2024-01-28 23:31
vm.swappiness is a modifier that changes the balance between swapping out file cache pages in favour of anonymous pages.

Red Hat recommends a value of 10 for database workloads.

A value of 0 shuts it off entirely. If one is curious to see, I would suggest adding a third row of 20 to lostgoat's template for comparison, i.e. 1, 20, 60. You don't need to reboot the system to do this, so it's easy enough to switch the value in the terminal.

**Comment by lostgoat** [comment] 2024-01-28 23:36
> You don't need to reboot the system to do this, so it's easy enough to switch the value in the terminal.

Reboots are pretty important when changing parameters of a test to ensure state doesn’t leak from one benchmark run to another.

Tests should also be run multiple times to detect outliers in measurements.

**Comment by Sunspark-007** [comment] 2024-01-28 23:40
> Reboots are pretty important when changing parameters of a test to ensure state doesn’t leak from one benchmark run to another.

Agreed, I am reading your comment after I finished editing my original message. For this purpose, would you agree that flushing the swap with swapon and swapoff performs the same job as a reboot?

**Closed as completed** 2024-03-02 01:02 UTC

**Comment by Saxtr0** [comment] 2024-06-01 14:27
Maybe because SteamOS is using ZRAM as a swap device?
It make sense to set high value for swappiness, you want to page out to swap because with ZRAM swap is in memory, and paging out to swap means compressing memory.

**Comment by jakubbys** [comment] 2024-06-06 19:40
Swappiness value
---
> Maybe because SteamOS is using ZRAM as a swap device? It make sense to set high value for swappiness, you want to page out to swap because with ZRAM swap is in memory, and paging out to swap means compressing memory.

You'll see less commonly `used` memory that wasn't locked with `mlock(2)` being pushed to `swap`.
The general idea is that you want more `actively used data` in ram and rarely accessed data in swap.      
Yes it just pushes more data to zram swap to be compressed, but if you compress/decompress memory too often you lose cputime, leading to possible stutters.     

https://docs.kernel.org/admin-guide/sysctl/vm.html#swappiness
`For in-memory swap, like zram or zswap, as well as hybrid setups that have swap on faster devices than the filesystem, values beyond 100 can be considered.`


Measurement metrics
---
>We haven’t seen workloads where this has a significant effect. But if anyone can provide comparisons in the following format that show that this change would be beneficial, then we are open to re-evaluate:

I think we can measure something that is a bit less relevant to the user, but displays a lot more the impact of those changes in a ram-starved/heavy swap use scenario.     
We can be measuring cputime used in the kernel space etc., but there's an even better metric that the kernel provides.     

The pressure stall information of the wasted cputime waiting on memory resource can be measured with `/proc/pressure/memory`.   
It's a metric of average(10,60,300 seconds) cpu time that could have been scheduled to other tasks, but couldn't because time has been wasted on memory(this includes time of memory mapped files which triggered a page-fault as well as zswap, zram and physical swap, note: there's no differentiation between the 4 things).           

You can read up more on PSI here:   
https://docs.kernel.org/accounting/psi.html
So instead of frametime data, the amount of cputime that wasn't scheduled to kernel/userspace tasks waiting for memory can be measured against some kind of base measurement.   


Swap organization
----
https://docs.kernel.org/admin-guide/mm/zswap.html
https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/tree/mm/Kconfig?h=v6.6.32#n48 | an interesting option
https://docs.kernel.org/admin-guide/blockdev/zram.html


The safest option `zswap -> nvme swap`.     
The 2 contenders here are the use of `lz4` or `zstd` algorithm (,?`lzo` I guess is also a valid option?).   
1. `lz4` will allow for bigger `max_pool_percentage` of the compressed swap page(it's much faster than `zstd` at a cost of lower compression ratio).    
2. `zstd` will provide higher compression ratio, but will lead to stuttering for higher max_pool_percentages(some of them are likely only reachable if `accept_threshold_percent` hysteresis is disabled anyway).      

Which ways I don't think isn't worth considering:    
1. zswap -> zram swap -> nvme swap. | First data attempts to get swapped into zswap cache. Gets pushed into zram swap. After zram swap fills up only then does data gets pushed to nvme swap. Zswap cache saves us here a bit, but nvme swap can now hold some of the more relevant newer more active pages than zram swap does.

What I'm unsure of:
1. zram swap. | Does the kernel supports `discard` parameter for swap, to mark the uncompressed zram space as unused? - frees up memory/triggers re-compression. Or does the kernel zero byte clear swap space - high compression ratio, triggers re-compression? Or does it keep the data in the swap file/partition unmodified(normally this approach reduces writes on SSD/HDD devices, which is a reasonable thing to do in those cases) - worst case scenario?    
2. `zswap -> zram swap` setup. | I think this is pretty good for having 2 compressed swap memory pools, with 2 different compression algorithms and different pool sizes(zstd for zram swap and lz4/lzo for zswap).

**Comment by ahydronous** [comment] 2024-08-15 12:09
I've spent an inordinate amount of time optimizing zram on my system.

### Benchmarks on `zstd-1` vs `lz4`
https://www.reddit.com/r/Fedora/comments/mzun99/new_zram_tuning_benchmarks/

### An explanation of vm.swappiness
https://docs.kernel.org/admin-guide/sysctl/vm.html#swappiness
https://stackoverflow.com/questions/72544562/what-is-vm-swappiness-a-percentage-of

### Overcommitting memory (zram being bigger than RAM size) is *good*
https://issuetracker.google.com/issues/227605780

### Gathered wisdoms
- Swap is usually written sequentially but read randomly
- Zram writes don't matter nearly as much as because Linux page cache data is already in RAM, and RAM>RAM transfers are absurdly quick
- Zram hardcoded blocksize is 4K
- For system memory performance applications care jack about bandwidth, latency (CAS etc in hardware, IOPS in software) is what matters
- You still want a swapfile, even with zram, due to the fact that you're gonna have incompressible or very idle pages that you want to evict from RAM. This goes double for the Deck, which will be RAM starved on some games due to the GPU claiming a lot of RAM. More on this later.

### IOPS benchmark on Samsung 970 EVO Plus 1TB
```
- lz4:            2 030 000 (!)
- zstd1:        820 000
- 970 EVO:  15 300
```

### Compression ratios on mixed data
```
- lz4:      2.1
- zstd1:  2.9
```
This is very relevant for the Deck, because <12GB is right where in a lot of scenarios the benefits of extra memory from `zstd1` start to outstrip the latency benefits of `lz4`.
Valve probably has a lot of profiled data, but as far as I've been able to tell, even the heaviest games don't go much over 4GB of VRAM.

### Swappiness
Swappiness can be derived via formula. On kernel.org, they state 
> For example, if the random IO against the swap device is on average 2x faster than IO from the filesystem, swappiness should be 133 (x + 2x = 200, 2x = 133.33).
You can reduce that to `(yx = 200 -x)`, where `y` is filesystem-to-swap IO ratio.
With the 970 Evo Plus as example again, we have aforementioned read IOPS values. `970EVO vs. lz4 =  15 300 / 2 030 000 = 0.008`, so `0.008` is our ratio.
We plug that in, `0.008x = 200 -x = 198.4`, and we get `vm.swappiness=198`.

### Page clusters
These are logarithmic. With zram, you get noticeable latency improvements with 1 page, `vm.page-cluster=0`

### Writeback device (backing swap partition)
https://www.kernel.org/doc/html/v5.9/admin-guide/blockdev/zram.html#writeback
Remember how I mentioned still needing a swapfile?
Here is where it gets slightly more convoluted.
- Zram currently only accepts swap partitions as a writeback device. 
- This swap partition can also not be the "ordinary" swap partition of the system, although I don't know if the Deck uses the swapfile for anything beyond. Thankfully you can replace the swapfile with the swap partition, effectively costing no extra space
- Currently, marking pages idle and evicting them has to be invoked via commensurate commands. This could be done via either `cron` or perhaps a `systemd` service. This will also need a writeback limit set to prevent wearing out SSDs, especially the 64GB eMMC Deck.

@bertogg 
@lostgoat
