### ISSUE TITLE
Add current display dimensions to the Display settings tab

### ISSUE THREAD

**Issue by Managor** [ValveSoftware/SteamOS#1456] opened 2024-03-27 14:33 UTC
#### Your system information

* Steam client version: 1711147596
* SteamOS version:  3.5.17
* Opted into Steam client beta?: Yes 
* Opted into SteamOS beta?: Yes
* Have you checked for updates in Settings > System?: Yes

#### Please describe your issue in as much detail as possible:
I wanted to quickly check the out the display dimensions that the deck is outputting in gamemode and I didn't find it in the place I expected to find it which is the Display tab nor in the System tab which is littered with system data.

**Comment by kisak-valve** [comment] 2024-03-27 14:48
Hello @Managor, please try to be a bit more careful with which issue tracker you chose to report issues in. Generally speaking, if an issue looks like it's related to the Steam client running on the Steam Deck or Steam Input, then that should be reported in the steam-for-linux issue tracker. If an issue looks like it's with SteamOS as a platform, then that fits in the SteamOS issue tracker.

**Comment by kisak-valve** [comment] 2024-03-27 14:50
Closing as a duplicate of #1435.

**Closed by kisak-valve** 2024-03-27 14:50 UTC

**Comment by Managor** [comment] 2024-03-27 14:52
I see, thank you. I have been avoiding posting on that tracker if I can't make sure that the issue is purely linux specific. I assumed the SteamOS tracker would encompass all of Steam Deck. I will adjust my reporting from now on.
