### ISSUE TITLE
Valve should reduce the flickering/PWM of the Steam Deck OLED screen so that users don't experience eye fatigue, migraines, and blurred vision

### ISSUE THREAD

**Issue by Sightlyjester** [ValveSoftware/SteamOS#1337] opened 2024-01-05 17:13 UTC
**Your system information**

* Steam client version: 1702079146
* SteamOS version: 3.5.7
* Opted into Steam client beta?: No
* Opted into SteamOS beta?:  No
* Have you checked for updates in Settings > System?: Yes

**Please describe your issue in as much detail as possible:**

Constant flicker of the screen because of PWM dimming of the screen leads to dry eyes, nausea and blurry vision to those sensitive to PWM.

Steam OS could introduce software measures (DC dimming) to limit the flickering and to reduce the physical effects to those affected. See detailed description of the issue below.

**Steps for reproducing this issue:**
1. Use Steam Deck at 100% brightness
2. Use for random amount of time
3. Eyes get dry and vision gets blurry, some report headaches.
4. Only gets worse with decreasing brightness of the screen, mainly below 45% brightness where the flickering is more aggressive, however PWM flickering is very aggressive in Steam Deck OLED at all brightness levels as you will see in my tests

**Detailed description of the issue**

I am posting here my evidence, which has been conducted in a scientific and objective manner, thanks to reliable instruments that any user can currently acquire on the internet like Opple light. Both  of my instruments (Opple Light Pro and Radex Lupin) measure various parameters, including flicker, and accurately classify whether a screen has aggressive and harmful flicker for eyesight and visual health, or if, on the contrary, it is a recommended screen for extended gaming sessions.

At the same time, I provide two possible solutions that could be implemented on the OLED panel of the Steam Deck through software to address the issue. These fixes can be applied through software, and many mobile manufacturers have successfully done so with their products, transforming a mobile device with aggressive flickering at launch into one that protects eyesight over time thanks to the patch.

This is the original post where I provide all the measurements and evidence that the PWM flicker of the Steam Deck OLED screen is harmful and very aggressive for the user as it comes from the factory settings on its panel in Reddit. I'm sharing it here so that the Steam Deck developers have more information at hand. However, I will also include the main information in this GitHub report:
https://www.reddit.com/r/SteamDeck/comments/1882kys/analysis_of_the_pwmflickervisual_fatigue_of_the/

### **This is my conclusion. See the above link of Reddit for the full report and screenshots:**

**CITATION OF THE IMPORTANT INFORMATION STARTS:**

The anti-glare Samsung OLED screen on the Steam Deck OLED has proven to be very harmful to the eyes during my gaming sessions, and the damage is particularly pronounced below 45% brightness. However, the high risk is common at all brightness levels equally according to my instruments. There will be a percentage of people with very low sensitivity to PWM flickering who will not notice negative symptoms in their eyes. However, another large percentage of people, especially the most sensitive, will experience symptoms.

Associated symptoms may include nausea, rapid eye discomfort or fatigue, a sensation of grit in the eyes, migraines, and general fatigue, blurred vision after playing.

It's important to note that each individual reacts differently, and although the values measured here offer an objective and recommended range for viewing, the response can vary from person to person. If you are particularly sensitive, I cannot recommend this screen for gaming, unlike the Steam Deck LCD screen, which is flicker-free. Some users may try it and not experience issues, but my data indicates that the risk of problems is VERY HIGH. This can be seen in the Reddit post I published, where at least 20% of comments are from people complaining that they had to return their Steam Deck OLED due to unpleasant symptoms in their eyes, as well as dizziness and blurry vision after playing.

Well, although the detailed information and explanations are in the Reddit link I provided above, here is a summary in the form of images and tests. First, I will show the flicker level at different brightness levels on Steam Deck OLED, and then I will compare those same brightness levels on Steam Deck LCD, confirming that the latter is within safe values for the eyes and that the OLED has a high risk of causing damage and discomfort during gaming sessions for several users:

In the Opple Light graphs, to prevent eye damage or fatigue, it should stay in the yellow-green zone, and in the Radex Lupin, the recommended percentage is 5% or below. If the percentage goes above 20%, it starts to become quite harmful:

**_Steam Deck OLED 100% Brightness:_**
![image](https://github.com/ValveSoftware/SteamOS/assets/105895386/6dcf686c-2fd3-4b72-b425-e540ca4e92ad)
![image](https://github.com/ValveSoftware/SteamOS/assets/105895386/df9d4fff-7415-459d-9c16-ab387c93f1b9)
![image](https://github.com/ValveSoftware/SteamOS/assets/105895386/3b14ac10-107c-4f7d-bcf6-bb3689459cc1)

**VS**

**Steam Deck LCD 100% Brightness:**
![image](https://github.com/ValveSoftware/SteamOS/assets/105895386/ad572f99-d8df-49bf-b243-a4e0be7e2f5a)
![image](https://github.com/ValveSoftware/SteamOS/assets/105895386/ac487b8e-0106-48d8-a688-bd4fe394c0a0)
![image](https://github.com/ValveSoftware/SteamOS/assets/105895386/e6dcb74d-c418-4601-8f44-07cfebf144e0)

**Steam Deck OLED 75% Brightness:**
![image](https://github.com/ValveSoftware/SteamOS/assets/105895386/d40c87a1-7f46-41e7-b68b-96620462634b)
![image](https://github.com/ValveSoftware/SteamOS/assets/105895386/f4af5337-f9e7-4e37-8628-a7ff827f72c9)
![image](https://github.com/ValveSoftware/SteamOS/assets/105895386/f38a803e-5e12-480d-951f-b70910d25bb9)

**VS**

**Steam Deck LCD 75% Brightness:**
![image](https://github.com/ValveSoftware/SteamOS/assets/105895386/ba57a187-3a0a-4c6a-ad13-e08fd47b39cd)
![image](https://github.com/ValveSoftware/SteamOS/assets/105895386/790b226b-58a2-4635-aa53-22c826b47792)
![image](https://github.com/ValveSoftware/SteamOS/assets/105895386/545d2df0-6d63-4b7c-b866-39ebf994fb7a)

**Steam Deck OLED 50% Brightness:**
![image](https://github.com/ValveSoftware/SteamOS/assets/105895386/5bb0cecd-db52-41ea-b6e8-43c85ce61f1d)
![image](https://github.com/ValveSoftware/SteamOS/assets/105895386/fc5728ae-3550-4eb9-9bfc-c919f1bb1268)
![image](https://github.com/ValveSoftware/SteamOS/assets/105895386/5638a341-d0e9-4793-b910-879b6cee6c5d)

**VS**

Steam Deck LCD 50% Brightness:
****![image](https://github.com/ValveSoftware/SteamOS/assets/105895386/ec508598-52b8-416a-bc3d-ebe6b14f7608)
![image](https://github.com/ValveSoftware/SteamOS/assets/105895386/e85cd0a8-8975-4ccb-ad41-d093ae007143)
![image](https://github.com/ValveSoftware/SteamOS/assets/105895386/8c2bcaaf-8f0e-4233-bba7-7280e783fa4d)

**Steam Deck OLED 45% Brightness:**
![image](https://github.com/ValveSoftware/SteamOS/assets/105895386/649c589e-d0f9-4b9f-b035-1296d3fef998)
![image](https://github.com/ValveSoftware/SteamOS/assets/105895386/fc64a5d3-470b-4722-b05c-d1a889bb9222)
![image](https://github.com/ValveSoftware/SteamOS/assets/105895386/cdd6597a-df7e-40de-bed6-cd313c7224f3)

**Steam Deck OLED 30% Brightness:**
![image](https://github.com/ValveSoftware/SteamOS/assets/105895386/fb1afd3d-cace-4a0a-9ae2-4dcef1256943)

**VS**

**Steam Deck LCD 30% Brightness:**
![image](https://github.com/ValveSoftware/SteamOS/assets/105895386/f0785fcb-3bd1-408f-8877-6bc1bfbbd373)
![image](https://github.com/ValveSoftware/SteamOS/assets/105895386/a32df3a7-f053-41dd-bbd6-8bfb48fc0273)
![image](https://github.com/ValveSoftware/SteamOS/assets/105895386/dc333d18-9860-4cbb-a79f-543392ec0cac)

**Steam Deck OLED 10% Brightness:**
![image](https://github.com/ValveSoftware/SteamOS/assets/105895386/026b6c0e-de0d-45e6-8c21-08255a46b817)
![image](https://github.com/ValveSoftware/SteamOS/assets/105895386/9bdc7258-c119-47aa-8d1d-64f01ab0471c)
![image](https://github.com/ValveSoftware/SteamOS/assets/105895386/0ef99f06-871d-44ff-9281-7820dc179cfb)

**Steam Deck LCD 0% Brightness:**
![image](https://github.com/ValveSoftware/SteamOS/assets/105895386/55fc6930-f0a1-4a17-90f8-8524705afc04)
![image](https://github.com/ValveSoftware/SteamOS/assets/105895386/cef9f442-6e77-4748-9b5a-4f33beeb11a6)
![image](https://github.com/ValveSoftware/SteamOS/assets/105895386/d5e4f8cd-dd2e-4f57-82e2-67bd364e985e)

**After this test and comparisons of the flicker of the screen of the two Steam Deck models, I want to focus on what Valve CAN change now regarding the PWM of the OLED screen to solve this problem:**

1- [Patch SteamOS by adding an option to enable DC-Dimming]: DC-Dimming is an alternative software method of regulating screen brightness that eliminates almost 100% of the flicker of screens of this style where I have tried it or has been implemented. For example, my Xiaomi Mi 9 phone with an Amoled screen and other Xiaomi Oled screens were unusable for me with the default PWM, but once DC dimming, also called "anti-flicker" mode, is activated, the phone is completely usable for hours without tiring. Valve is a company known for listening to and supporting its community and consumers by implementing their requests in software with new updates. **[With this measure, Valve could reduce a high percentage of people who end up with eye fatigue and worse health playing their OLED steam decks to basically almost nothing. It is about offering a product that takes care of your customers' eyes.

2- A second option by Valve could be, instead of implementing a DC Dimming mode, that the screen still uses PWM but increase its PWM frequency from 360Hz to 1100Hz. Look at what happens when the Hz frequency on the Steam Deck LCD reaches this value, even at its worst flicker percentage (99%), it manages to enter the yellow or green zone.

![Screenshot-2023-11-13-17-54-56-412-com-opple-lightmasterpro](https://github.com/ValveSoftware/SteamOS/assets/105895386/83574b81-290a-4ddc-98d1-2867a4e8c54f)

Image of Steam Deck LCD at its worst flicker value, which is mitigated by high frequency; the rest of its values are almost always flicker-free. Steam Deck LCD is the recommended product for people sensitive to this phenomenon, at least for now.

Examples of implementations that companies and manufacturers integrate through software on mobile devices such as Huawei, Xiaomi, or Oppo with Oleds PWM displays. From options to activate DC Dimming in normal, adaptive, or hybrid mode, to a software-based increase in the panel's PWM hertz to minimize the perception of flicker, this can be added and patched with software updates.

![w84l16091q3c1](https://github.com/ValveSoftware/SteamOS/assets/105895386/0d18e4a3-f0f8-4fc6-93ce-453f6411985b)

![483eg6091q3c1](https://github.com/ValveSoftware/SteamOS/assets/105895386/fcfdd8c0-9d97-42cf-8897-5e3c164e8d4a)

Here is the previous PWM analysis I did of the Steam Deck LCD so that you can compare it with the OLED at each brightness level. The LCD panel is almost flicker-free 100%, entering the green zone at all its brightness levels except at 30%, which stays yellow: [(44) Analysis of the PWM of the Steam Deck LCD screen and its level of visual fatigue (and the same style of analysis for Steam Deck OLED next week) : SteamDeck (reddit.com)](https://www.reddit.com/r/SteamDeck/comments/17yf90o/analysis_of_the_pwm_of_the_steam_deck_lcd_screen/)

While in my use of the Steam Deck LCD Anti-Glare for hours, my eyes have never gotten tired; with Steam Deck OLED, I have already experienced eye strain and a feeling of blurry vision after playing or shortly after starting.

**CITATION OF THE IMPORTANT INFORMATION ENDS**

**Additional Information:** If any Valve developer wants to better understand the flickering concept presented in the tests in this GitHub report, in the original post I made on Reddit, I explain technically what the quantity of hertz in the flickering frequency means, as well as the level and percentage of flickering modulation, and how to interpret the influence of both factors at each brightness level: https://www.reddit.com/r/SteamDeck/comments/1882kys/analysis_of_the_pwmflickervisual_fatigue_of_the/

**Comment by esotericode** [comment] 2024-01-06 02:35
Thank you for this detailed and wonderful writeup. I have nothing more to add than I really hope that Valve addresses this issue either as a hardware or software fix.

**Comment by x-ider** [comment] 2024-01-06 04:36
Thank you so much for your research! I've been playing video games long hours my whole life but never experienced consequences so dramatic!
I haven't measured precisely but after 2 days of having my Steam Deck OLED 512GB I can tell that eye strain comes after 20-30 minutes and headache kicks in after an hour of playing. Not sure I'll wait possible patches, rather return it.

P.S. Leet issue number, you guys have to fix it now for sure

**Comment by wx40217** [comment] 2024-01-06 12:01
I don't have a noticeable sensation, but I also pay great attention to this issue. It is essential to give users the option to sacrifice some display effects in exchange for eye protection.

**Comment by snipem** [comment] 2024-01-06 15:08
Thank you for this issue.

I had to send my OLED unit back because my eyes got dry and fuzzy after using the Steam Desk OLED. I never had this experience with any other device than Steam Deck OLED.  I also saw an optometrist who said my eyesight was perfect. After not using the Steam Deck OLED for some weeks my eyes are back to normal without any problems.

**Comment by rpafran** [comment] 2024-01-08 10:47
Totally agree. With the LCD model I can play hours without problems, but with the oled if the brightness is under 80% i feel dry eyes and headache. I Hope that valve can patch this issue. Thanks to jester for all the work.

**Comment by xsxavier** [comment] 2024-01-09 10:29
This is a good suggestion and mostly well researched and extra options like this are always welcome. 

However, I'd like to add a note of caution regarding medical claims that cannot be proven, this diminishes the integrity of your actual research. 
While your research is detailed, it's important to distinguish between discomfort and temporary symptoms, and permanent health damage. There is to date no scientific proof whatsoever that looking at screens too long, sitting too close and pwm-flicker cause damage to your eyes or health. These factors can indeed lead to temporary discomfort for some users, such as eye strain, headaches, or nausea, they will not cause any permanent damage to your health.

I appreciate your effort in compiling this data though and this will help to improve Steam-OS.

**Comment by andrewcharlton87** [comment] 2024-01-09 20:31
This is an important issue which should not be ignored, there should be an "eye friendly" option to reduce PWM flicker at the cost of colour accuracy/smoothness.

People who are PWM sensitive will avoid using a screen this aggressive, and by all accounts it is a relatively simple software fix. I have refunded my SD OLED and will only repurchase once this issue is resolved unfortunately.

**Comment by manub** [comment] 2024-01-10 09:43
Thank you for reporting this! I wear prescription glasses but I never experienced other vision issues. After a 1h session on my Steam Deck OLED, I notice blurred vision which will go away within 5 minutes after stopping playing. While I could dock the SD to an external screen to avoid this issue, this defeats the purpose of a portable device. I look forward to hearing feedback from Valve.

**Comment by mguilherme** [comment] 2024-01-13 02:02
Sadly it seems I have the same issue!
I was already experiencing this with the LCD model but it’s even worse with the Oled model.

I can use my iPhone for hours but my eyes can’t stand 30m of game play on the steam deck

**Comment by manub** [comment] 2024-01-14 21:30
I have reported the issue to Steam support which replied saying they're not aware of it. Has anybody here who experienced similar eye fatigue symptoms opened a ticket?

**Comment by mguilherme** [comment] 2024-01-15 00:41
> I have reported the issue to Steam support which replied saying they're not aware of it. Has anybody here who experienced similar eye fatigue symptoms opened a ticket?

I didn’t, but I would expect to be faster with a GitHub issue!

**Comment by snipem** [comment] 2024-01-15 18:25
@Sightlyjester Do your solution options work with the LCD display as well? Could you update your issue, mentioning that people experiencing the same with the LCD model? One source of many:
https://www.reddit.com/r/SteamDeck/s/pF0TZ3s5Gr

**Comment by carpaltunnel** [comment] 2024-01-27 23:49
Same problem here.  The OLED Deck is my first portable since a PSP and if I play it for more than 15min then a few hours later my eyes are bloodshot, burning, continually leaking tears, and very painful.  I've been staring at screens for 10 - 18 hours a day for 25+ years now and the Deck is the only new thing in my routine.

The problem doesn't happen if I dock it to a TV so that seems to leave the Deck screen as the likely culprit.  It's nice that I can still use it docked, but then I lose 50% of the reason for having it which is portable play on business trips.

**Comment by andrewcharlton87** [comment] 2024-01-28 20:50
> Same problem here. The OLED Deck is my first portable since a PSP and if I play it for more than 15min then a few hours later my eyes are bloodshot, burning, continually leaking tears, and very painful - persisting for around 48 hours. I've been staring at screens for 10 - 18 hours a day for 25+ years now and the Deck is the only new thing in my routine.
> 
> The problem doesn't happen if I dock it to a TV so that seems to leave the Deck screen as the likely culprit. It's nice that I can still use it docked, but then I lose 50% of the reason for having it which is portable play on business trips.

You shouldn't have to do this, but as a general solution I've found gradual exposure to PWM screens to help. For example, I will start off by setting a 10 minute timer on my watch while playing, then take a 3 minute break. Repeat for the entire session for a week or so. Then build to 20 minutes/3 rest, 30/3 etc.

I find this helps adjust, but it may not work for everyone. I have never built up to a point where taking a break is optional. 

The optimal solution is for valve to find a fix.

**Comment by Malamo999** [comment] 2024-02-15 17:43
Thank you for all the research and testing you've done to highlight this issue.

**Comment by hungrymonkey** [comment] 2024-02-18 01:40
> This is an important issue which should not be ignored, there should be an "eye friendly" option to reduce PWM flicker at the cost of colour accuracy/smoothness.
> 

I want to laugh a bit. Sometimes I believe Valve is making a next gen VR headset and wants to update it to modern standards. If they are making one, I believe the OP threw a wretch in their plans a bit because Valve realize they have to fix this multi million dollar mistake.

They probably are taking this issue seriously. Gotta fix their other mistakes too. Either way, good job OP. You added a verifiable test to Valve toolkit. I always wonder why it was annoying to look at my OLED phone. I hope you will benefit from any proposed PWN workaround or fixed.

**Comment by mguilherme** [comment] 2024-02-18 14:22
Unless this starts to be seen on top YouTube channels **valve** won’t do anything 🙁

**Comment by hungrymonkey** [comment] 2024-02-18 14:48
> Unless this starts to be seen on top YouTube channels **valve** won’t do anything 🙁

Why do you think that? I like to think the OP threw a wretch in Valve's VR plans. Valve probably wants to modernize the Index. Since this many people are sensitive to this stuff, even more people will have issues in VR. This problem might be inherent in the panels itself. I wonder whether Valve needs to re-negotiate contracts and find less painful panels.

**Comment by mguilherme** [comment] 2024-02-18 14:52
> > Unless this starts to be seen on top YouTube channels **valve** won’t do anything 🙁
> 
> Why do you think that? I like to think the OP threw a wretch in Valve's VR plans. Valve probably wants to modernize the Index. Since this many people are sensitive to this stuff, even more people will have issues in VR. This problem might be inherent in the panels itself. I wonder whether Valve needs to re-negotiate contracts and find less painful panels.

Being a former SD lcd owner and now an Oled owner I really would like this to be solved.
I’m just saying that if the top SD YouTubers start to talk more about this maybe Valve would do something

**Comment by andrewcharlton87** [comment] 2024-02-18 16:07
> > > Unless this starts to be seen on top YouTube channels **valve** won’t do anything 🙁
> > 
> > 
> > Why do you think that? I like to think the OP threw a wretch in Valve's VR plans. Valve probably wants to modernize the Index. Since this many people are sensitive to this stuff, even more people will have issues in VR. This problem might be inherent in the panels itself. I wonder whether Valve needs to re-negotiate contracts and find less painful panels.
> 
> Being a former SD lcd owner and now an Oled owner I really would like this to be solved. I’m just saying that if the top SD YouTubers start to talk more about this maybe Valve would do something


Unfortunately I suspect you are correct. Valve haven't even acknowledged the issue, there's nothing to suggest they're working on a fix as things stand. 99.99% of SD owners are probably unaware that this issue even exists.

**Comment by Sightlyjester** [comment] 2024-02-21 00:28
We continue the report of this problem in this new post that I have opened, since in this the report number is 1337 and it is giving me problems to share it externally with its link because the bots of certain pages like Reddit falsely ban it believing that it is a piracy post:
https://github.com/ValveSoftware/SteamOS/issues/1392

**Comment by lostgoat** [comment] 2024-02-21 05:01
Closing as a duplicate of #1392 as requested by the author.

**Closed by lostgoat** 2024-02-21 05:01 UTC
