### ISSUE TITLE
Ctrl+Alt+F2 thru F6 TTY terminals

### ISSUE THREAD

**Issue by lineber** [ValveSoftware/SteamOS#603] opened 2017-07-30 06:36 UTC
Intel Pentium G4620 CPU
MSI B250I Gaming Pro AC Mini-ITX Motherboard
16 Gb RAM
ASUS GTX 1060 3gb graphics card

* Steam client version: 1500335472
* SteamOS version: 2.0 1:2.117
* Opted into Steam client beta?: No
* Opted into SteamOS beta?: No
* Have you checked for updates in Settings > System?: Yes

#### Please describe your issue in as much detail as possible:
I use Ctrl+Alt-(F2,F3,F4,F5,F6) to switch from Big Picture Mode to a TTY terminals. However, recently I just go to a blank screen. This was very convenient to have a terminal with VIM for instance, so I can make notes without having to log out of a game.

I really hope that Valve is not disabling this feature, as it is something only people who understand Linux know to use. Makes it very functional if you know how to do things on a command line. 

#### Steps for reproducing this issue:

1. In BPM
2. Press Ctrl+Alt+F{2-6}
3. Switches to a blank screen and places monitor in sleep mode. Press Ctrl+Alt+F7 to return to the game.

**Comment by lineber** [comment] 2017-07-30 06:51
Please delete this, I figured it out. I ran the following command and rebooted. Now works as it should.

sudo /etc/init.d/lightdm stop

**Comment by kisak-valve** [comment] 2017-07-31 13:41
Hello @lineber, as far as I know, nVidia has had a long-standing stance that switching to/from VTs with their driver can cause unexpected behavior because the framebuffer is outside the control of the nvidia kernel module. This behavior is not related to steam and your mileage will vary.

Closing per the request in the comment.

**Closed by kisak-valve** 2017-07-31 13:41 UTC
