### ISSUE TITLE
Blank screen after exiting game.

### ISSUE THREAD

**Issue by RyanHakurei** [ValveSoftware/SteamOS#1109] opened 2023-07-29 23:17 UTC
#### Your system information

* Steam client version:1690583737
* SteamOS version: 3.4.8
* Opted into Steam client beta?: Yes
* Opted into SteamOS beta?: Yes 
* Have you checked for updates in Settings > System?: Yes

#### Please describe your issue in as much detail as possible:
After existing a game I am presented with a blank screen. I can hear UI sound effects so everything is working behind the scenes, but the screen is not displaying anything. The only way I've found out of this is a hard reboot. Sometimes I can get the display to output something when I bring up the power menu, but this is very intermittent. 
[PXL_20230729_225037454.TS.webm](https://github.com/ValveSoftware/SteamOS/assets/5086636/05ad384d-d605-4739-9799-852eaf217015)

#### Steps for reproducing this issue:

1. Launch game
2. Exit game
3. Blank screen.

**Comment by allenfoxtc** [comment] 2023-07-30 05:37
> Opted into Steam client beta?: Yes

this should be the problem. try revert to stable version.

**Comment by guilhermepiccoli** [comment] 2023-07-30 16:18
Thanks for the report! I'm not sure if you have any form of accessing your Deck remotely, like SSH. But if so, would be really useful if you could collect the output of `dmesg`  and `journalctl -b ` and attach them here, when the issue reproduces.

Cheers!

**Comment by MsRiaCayde** [comment] 2023-07-30 18:19
Part of the issue I'm facing is that, after this occurs I restart the deck and attempt to load but due to having Clover boot manager (no other OS though) I'm unable to select through as there's no way to use the internal controls. While this is a modification issue layered ontop of the OS issue, unsure how to proceed as I don't know if it's possible to complete a flash/etc without having some form of controls.

**Comment by guilhermepiccoli** [comment] 2023-07-31 03:43
Thank you @RyanHakurei ! But it seems everything is fine due to the logs - did you collected them *right after the issue*?

Dmesg shows that the Deck was resuming from suspend. Also, if not a problem for you, please collect the full dmesg logs and attach it here instead of just a snippet - you could either attach the file in a comment or use some pastebin service.

Thanks!

**Comment by leandrorosa** [comment] 2023-07-31 13:50
Hello, I am also facing the same issue. Was using the stable channel when it started to happen, I also tested with beta channel and the problem is still happening.

Was able to fetch `dmesg` and `journal` logs using `ssh` though.

[journalctl.log](https://github.com/ValveSoftware/SteamOS/files/12215644/journalctl.log)
[dmesg.log](https://github.com/ValveSoftware/SteamOS/files/12215645/dmesg.log)

**Comment by leandrorosa** [comment] 2023-08-01 07:00
Hi I have got my problem fixed by uninstalling all my plugins (except Porwer Tools and Vibrand Deck) and disabling "Updated  fan control" 

I have got this from Valve Support: 
```
Hi, 

Thanks for the information.

We recommend to disable "Enable updated fan control". Please follow the steps below:
Use the Steam button > Settings > System > and near the bottom of that page in the Advanced section you should see the "Enable updated fan control" setting.
Disable the setting.
Use the Steam button again > go to Power > select Restart
After the system restarts, retest the issue again.

Important: If disabling the "Enable updated fan control" setting fixes or improves the issue, please let us know.

If you are using any external plugins on your Deck, we also recommend that you temporarily disable all external plugins (some plugins have been known to cause severe performance issues) and retest to see if the problem still exists.

If you are still having the problem, please write back and we will assist further.

Steam Support
Deppy
```

Hoppe that this can also help you.

**Comment by sirocyl** [comment] 2023-08-01 21:09
Noticed the same behavior on my Deck, beta or stable client. I've got devkit tools plugged onto it, so I'm gonna take a quick look at triaging this, but I do notice that this is reproducible by ***pressing the volume keys***, even after a Steam client restart/reboot. As soon as the volume overlay disappears, the video goes black, while the system is still running behind the black screen.

If it is due to plugins or their settings, I'll bisect which one exactly is causing this.

**Comment by sirocyl** [comment] 2023-08-01 21:53
@RyanHakurei are you using any Decky Loader plugins? If so, could you share a list? And do you have DeckFAQs installed?

_You can list all your installed plugins quickly with an `ls ~/homebrew/plugins` from a command line._

**Closed as completed** 2023-08-04 16:56 UTC
