### ISSUE TITLE
[request] Printer/CUPS support in SteamOS

### ISSUE THREAD

**Issue by Knochi** [ValveSoftware/SteamOS#914] opened 2022-11-19 07:35 UTC
#### Your system information

Operating System: SteamOS 3.3.2
KDE Plasma Version: 5.23.5
KDE Frameworks Version: 5.90.0
Qt Version: 5.15.2
Kernel Version: 5.13.0-valve21.3-1-neptune (64-bit)
Graphics Platform: X11
Processors: 8 × AMD Custom APU 0405
Memory: 14,5 GiB of RAM
Graphics Processor: AMD Custom GPU 0405

* Opted into Steam client beta?: No
* Opted into SteamOS beta?: No
* Have you checked for updates in Settings > System?: Yes

#### Please describe your issue in as much detail as possible:
I known this has been request [long time ago](https://github.com/ValveSoftware/SteamOS/issues/186) but now it's 2022 and more users, as i do, are trying to use SteamDeck beside it's fantastical gaming abilities as work PC.

So I would like to see CUPS support in a future release of SteamDeck.

#### Steps for reproducing this issue:

1. open document
2. select "print"
3. try to setup printer

**Comment by psychollek** [comment] 2022-12-17 16:11
It is actually a first thing I found missing from steamdeck for using it as my work computer :D

**Comment by rgreening** [comment] 2023-01-02 20:59
Yes, please add support for printing. I do not understand the logic to strip this from the SteamOS (Arch Linux) base install. It is a common task on all desktops.

**Comment by waspennator** [comment] 2023-06-05 22:52
Would be nice to see this for steamos 3.5 or sometime in general.

**Comment by adarsh1001** [comment] 2023-07-15 10:02
+1 on this. It would have been another story if SteamOS didn't expose a proper KDE desktop but since it does, CUPS preinstalled would be nice to have.

**Comment by FearNaBoinne** [comment] 2023-08-22 21:14
I would like to add my support to this request! I can do most everything I need on a daily basis on my Steam Deck as a lightweight PC alternative, but printing support is something I regularly find myself missing!
(That and a proper macro tool like AutoKey or such)

**Comment by jg00dman** [comment] 2023-11-20 19:37
Printing is a basic function which is needed. Please add this. It was easy when pacman worked before Steam OS 3.5.5.

**Comment by FearNaBoinne** [comment] 2023-11-20 19:43
Pacman still works?

I reinstalled CUPS after the 3.5.5 update...

**Comment by bertogg** [comment] 2023-11-20 22:36
Hi, SteamOS 3.5 comes with podman and distrobox, maybe you can run the CUPS server inside a container ?

**Comment by jg00dman** [comment] 2023-12-04 17:35
> Pacman still works?
> 
> I reinstalled CUPS after the 3.5.5 update...

I get unresolvable conflicts when I try to do the install.

**Comment by Colcobau** [comment] 2024-03-01 18:22
+1 to this feature request. I use my Steamdeck as my daily driver, and not having print support is kind of a pain.

**Comment by bertogg** [comment] 2024-04-19 14:09
FYI the `20240418.1000` build comes with cups preinstalled, I'll let you know when it's available in SteamOS 3.6 beta in case you want to test it before the stable release.

**Comment by bertogg** [comment] 2024-05-15 09:02
This is available now in SteamOS 3.6, currently in preview. If anyone tries this and finds problems please report them here, thanks!

**Comment by rgreening** [comment] 2024-05-19 16:16
It works! Yes. I have a couple of HO inkjet/deskjet printers and this now works out of the box. To add scanning capability i installed the scanner flatpak from discover store. Worked as well.

For some Laserjets it may still require the HPLIP flatpak package (hp-setup utility to run from command-line). I haven't tested this yet as i am away from the Laserjet for a few months. But when i set it up manually last time it did. Unfortunately, HPLIP flatpak is no longer present in repository. I would be nice to add to flathub.

Thanks for adding CUPS. This is amazing!

**Comment by JLP** [comment] 2024-05-20 18:11
I can confirm it also works with an HP printer we have here. Thanks a lot!

**Comment by kisak-valve** [comment] 2024-05-31 12:25
Closing as implemented in SteamOS 3.6.

**Closed by kisak-valve** 2024-05-31 12:25 UTC
Labels: Need Retest

**Comment by Knochi** [comment] 2024-06-25 09:10
So now that we have cups, how do i setup my network printer? It's a CANON TS5151 Scanner-Printer
