### ISSUE TITLE
Official Docking Station VRR - LG OLED TV Freesync - No output when waking up from sleep mode or shutdown.

### ISSUE THREAD

**Issue by drnaniwat** [ValveSoftware/SteamOS#1574] opened 2024-07-16 20:06 UTC
#### Your system information

* Steam client version: 1720650399
* SteamOS version: 3.6.8
* Dock Firmware Version: 0.13.15.124
* Opted into Steam client beta?: Yes 
* Opted into SteamOS beta?: Yes 
* Have you checked for updates in Settings > System?: Yes

#### Please describe your issue in as much detail as possible:

Using an LG C2 television with an HDMI 2.0 cable with Freesync Mode enabled on it, I was able to consistently have my steam deck docking station to produce no image on the television when the VRR mode is on. Afterwards, even if the VRR mode is off on the steam deck, no images would be produced as long as Freesync is enabled on the television.

I have tested this on 1440p120 and 1080p120 resolutions. I had also tested it with the official charger connected directly to the electrical socket.

#### Steps for reproducing this issue:

1. Activate Freesync mode with VRR turned on in the quick menu.
2. Shut down the Steam Deck or put it into sleep mode.
3. Wake it up.

#### Alternative approaches to 'avoid' this problem.

1. Disconnect the USB-C that is connected to the charger.
2. Disable Freesync mode with VRR turned off.
3. Disconnect the USB-C connecting to the Steam Deck, and reconnect.

**Comment by kisak-valve** [comment] 2024-07-16 20:11
Hello @drnaniwat, there's no value in fragmenting the discussion of this issue across multiple issue reports.

Closing as a duplicate of #1512.

**Closed by kisak-valve** 2024-07-16 20:11 UTC
