### ISSUE TITLE
Steam Deck OLED Cant Open Forza Horizon 4. LCD Deck Can. Problem with fullscreen mode

### ISSUE THREAD

**Issue by ffrasisti** [ValveSoftware/SteamOS#1306] opened 2023-12-12 06:52 UTC
#### Your system information

Steam Deck OLED 1TB
* Steam client version: latest stable
* SteamOS version: 3.5.7
* Opted into Steam client beta?: [No] 
* Opted into SteamOS beta?: [No] 
* Have you checked for updates in Settings > System?: [Yes]

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen.
I opened Forza Horizon 4, intro videos do not play, but the game menu doesnt either. Depending on luck, it either shows a complete black screen instead of the game menu or the games logo and the press a to star prompt, which is unresponsive.
I was able to log into xbox when prompted but can start the game or interact with the menu in any way.
I tried Proton experimental and 8.04 and neither can do it. I tried checking if ALT+Enter can change windows. No dice
The game runs with proton 8.0.4 on my lcd decks

Here's more users reporting the same thing with the oled
https://steamcommunity.com/app/1293830/discussions/0/4029095496766340440/

Video:
https://drive.google.com/file/d/1YPQYB-jQ3BDN5EWE0-zNzbiulgxGzC3K/view?usp=sharing

#### Steps for reproducing this issue:

1. On a OLED Steam Deck, Open Forza Horizon 4 from GameMode
2. Attempt to play or interact with the menu.

EDIT:
https://www.protondb.com/app/1293830#OKAlcLVWz4 user here found a fix, hope valve can adress it, its oled specific
Game can not start with full screen enabled.

**Comment by ffrasisti** [comment] 2023-12-12 07:00
https://www.protondb.com/app/1293830#OKAlcLVWz4 user here found a fix, hope valve can adress it, its oled specific

**Comment by ffrasisti** [comment] 2023-12-12 07:04
@lostgoat

**Comment by waspennator** [comment] 2023-12-12 23:53
Curious if this is the same issue thats causing Sine Mora ex to boot to a black screen on oled decks, don't have the game to check but apparently seen reports that it only works on lcd decks or in desktop mode.

**Comment by waspennator** [comment] 2023-12-14 00:37
New steamos preview build dropped and I saw this in the log.

"Fixed black screen when launching Forza Horizon 4 and other titles on Steam Deck OLED"

**Comment by EXPERIMENTONGOD** [comment] 2023-12-27 17:06
> Curious if this is the same issue thats causing Sine Mora ex to boot to a black screen on oled decks, don't have the game to check but apparently seen reports that it only works on lcd decks or in desktop mode.

Yes it's the same. I just update to 3.5.12 Preview and Sine Mora EX now launches correctly.

Guys just set Steam Deck to get preview updates and save some headaches.

**Comment by waspennator** [comment] 2024-03-03 01:02
Fix should be in the latest stable release, so I believe this can be closed now.

**Comment by andrewiankidd** [comment] 2024-03-16 15:53
Still happening

**Comment by kisak-valve** [comment] 2024-05-10 23:37
Closing per "Fixed black screen when launching Forza Horizon 4 and other titles on Steam Deck OLED." in the [SteamOS 3.5.17](https://store.steampowered.com/news/app/1675200/view/4124805233776242149) update.

**Closed by kisak-valve** 2024-05-10 23:37 UTC
Labels: Need Retest

**Comment by drdaz** [comment] 2024-07-02 18:37
This issue seems to have returned.

**Comment by drdaz** [comment] 2024-07-11 10:19
@zezke I've got it working, but the workaround seems to be a little more complex now than it used to be - it's more than just disabling fullscreen. I used the guide in this video: https://www.youtube.com/watch?v=Wk7q55ujryY

It's still simple enough, and the game runs great once you get it going.

**Comment by waspennator** [comment] 2024-07-11 13:28
@kisak-valve 
Can this issue be reopened?

**Comment by ffrasisti** [comment] 2024-07-11 13:59
Maybe create another ticket if not? Sucks this is backEl 11 jul. 2024 10:29, waspennator ***@***.***> escribió:
@kisak-valve
Can this issue be reopened?

**Comment by waspennator** [comment] 2024-07-11 14:02
I don't have the game to make the report, so whoever here has the issue is gonna have to.
